/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Adventures': '冒险',
    'All Recipes': '所有配方',
    'Applicable Heroes': '适用英雄',
    'available for Upgrades.': '可用于升级。',
    'Heroes': '英雄',
    'Inventory': '库存',
    'Clear Save': '清除存档',
    'Details': '详情',
    'Download Save': '下载存档',
    'Dungeons': '地下城',
    'Equipment': '装备',
    'Exit Dungeon': '退出地下城',
    'Export Save': '导出存档',
    'Fetching...': '正在获取...',
    'Floor': '层',
    'Guilds': '公会',
    'Guild Workers': '公会工人',
    'Gold & Inventory': '黄金&库存',
    'Guild Recipes Available for Mastery': '公会配方可用于精通',
    'Market': '市场',
    'Inventory': '库存',
    'Heroes': '英雄',
    'Import Save': '导入存档',
    'Quests': '任务',
    'Sell All Commons': '出售所有普通物品',
    'Recipes': '配方',
    'Settings': '设置',
    'Sort Inventory': '库存排序',
    'Time Played': '游戏时长',
    'Town': '小镇',
    'Turn Order': '回合顺序',
    'View Bank': '查看银行',
    'Upgrades': '升级',
    'Equip': '装备',
    'LVL': '等级',
    'Knife': '刀',
    'Knives': '刀',
    'Hats': '帽子',
    'Hat': '帽子',
    'Staff': '法杖',
    'Staffs': '法杖',
    'A Cool Dark Chainmail': '酷黑锁子甲',
    'Armors': '盔甲',
    'Armor': '盔甲',
    'Belts': '腰带',
    'Belt': '腰带',
    'Balmungous': '香脂',
    'Buzzblade': '嗡嗡之刃',
    'Cannonballer': '炮弹发射器',
    'Cauldroning': '大锅',
    'Clogs': '木屐',
    'Sell': '出售',
    'Shoes': '鞋子',
    'Sticks': '棍棒',
    'Staves': '权杖',
    'Squeaks': '吱吱',
    'The Bank': '银行',
    'Titan': '泰坦',
    'Tomes': '书籍',
    'Type': '类型',
    'Vest': '背心',
    'Vests': '背心',
    'View Links & Resources': '查看链接&资源',
    'Worker': '工人',
    'Wisdom': '智慧之盾',
    'You have': '你有',
    'Your Adventure Party': '你的冒险队伍',
    'Level': '等级',
    'Masks': '面具',
    'Mask': '面具',
    'Ring': '戒指',
    'Rings': '戒指',
    'Lactuca': '翡翠戒指',
    'Glove': '手套',
    'Sabre': '军刀',
    'Gloves': '手套',
    'Gauntlets': '护手',
    'Informing the uninformed...': '通知不知情的人...',
    'Initializing game...': '正在初始化游戏...',
    'Crawling the dungeons...': '地牢爬行...',
    'Constructing buildings...': '构建建筑...',
    'Finalizing your progress...': '正在完成进度...',
    'Gathering materials...': '收集材料...',
    'Gathering your heroes...': '聚集你的英雄...',
    'Helmets': '头盔',
    'Helmet': '头盔',
    'Jawstriker': '颚击者',
    'Item Being Equipped': '物品已被装备',
    'No materials currently in your inventory. Try the dungeons!': '您的库存中目前没有材料。去地下城试试!',
    'Not defeated yet.': '还没有被打败。',
    'Assembling the guilds...': '组装公会...',
    'Green Guard': '绿卫队',
    'Health': '生命值',
    'Not Completed': '未完成',
    'Boots': '靴子',
    'Boot': '靴子',
    'Swords': '剑',
    'Sword': '剑',
    'Stones': '石头',
    'Shield': '盾牌',
    'Shields': '盾牌',
    'Seeker': '探索者',
    'Thrown': '投掷',
    'Words': '词缀',
    'Trinket': '饰品',
    'Whalers': '捕鲸者',
    'Cloaks': '披风',
    'Cloak': '披风',
    'Pendants': '吊坠',
    'Pendant': '吊坠',
    'Shuriken': '手里剑',
    'Loafers': '懒人拖',
    'Loafer': '懒人拖',
    'Mastered': '已精通',
    'Materials': '材料',
    'Max Level!': '最高级！',
    'Max Level Reached!': '达到最高级！',
    'Milestone Markets': '里程碑市场',
    'Tawny': '茶色',
    'Purchase': '购买',
    'Patience': '耐力',
    'Plate': '板甲',
    'Kite': '风筝',
    'Renae': '雷那',
    'Recipe': '配方',
    'Power': '力量',
    'Locked': '未解锁',
    'Good Craft!': '好手艺!',
    'Fighter': '斗士',
    'The Forge': '锻造厂',
    'Trinkets': '饰品',
    'Tiny': '蒂妮',
    'The Marketplace': '市场',
    'The Cat\'s Meow': '猫喵喵',
    'The amount of damage an entity is capable of dealing.': '一个实体能够造成的伤害的数量。',
    'The amount of damage an entity can sustain before being downed.': '一个实体在被击倒前所能承受的伤害。',
    'Grogmar': '格罗格玛',
    'Revere': '里维尔',
    'Titus': '提图斯',
    'Troy': '特洛伊',
    'Neve': '尼芙',
    'Zoe': '佐伊',
    'Lambug': '林虫',
    'Grim': '格里姆',
    'Beorn': '贝恩',
    'Cedric': '塞德里克',
    'Caeda': '凯达',
    'All Folks Hat': '全民帽',
    'Alok': '阿洛克',
    'Francis': '弗朗西斯',
    'Gilbert': '吉尔伯特',
    'Gilfred': '吉尔弗雷德',
    'Gilda': '吉尔达',
    'Truth Teller': '吐真者',
    'The Mind Cap': '精神帽',
    'The Bloopinator': '吸血器',
    'That\'s Not A Knife': '这不是刀',
    'That\'s A Knife': '这是一把刀',
    'Total Commons Crafted': '总计制作的普通物品',
    'Total Epics Crafted': '总计制作的史诗级物品',
    'Total Floors Beaten': '总计打过的楼层',
    'Total Gold Earned': '总计赚取的黄金',
    'Total Goods Crafted': '总计制作的不错的物品',
    'Total Items Crafted': '总计制作的物品',
    'Total Greats Crafted': '总计制作的大师级物品',
    'Your progress for total bosses defeated.': '你总计击败的Boss进度。',
    'Your progress for perks purchased from the Market.': '从市场购买的福利的进度。',
    'Your progress for donations to the Museum.': '您捐赠给博物馆的进度。',
    'Visit our Subreddit': '访问我们的Subreddit',
    'Unmastered': '未精通',
    'Thanks for checking us out, unfortunately, we don\'t support a screen of this size. Please visit us on your computer, laptop or on a device with a larger screen.': '感谢您的关注，不幸的是，我们不支持这种尺寸的屏幕。请使用您的电脑、笔记本电脑或屏幕更大的设备访问我们。',
    'Residing in the Rapid Chi Orchard, these stoic beings are superb at defense.': '居住在拉皮奇果园（Rapid Chi Orchard）中，这些坚忍的生物在防御上非常出色。',
    'Purchase new recipes unlocked by leveling up your guild.': '购买通过升级公会解锁的新配方。',
    'Purchase unique upgrades and perks that will expand your capabilities.': '购买独特的升级和福利，将扩展您的功能。',
    'Playbooks offer up different hero skills. Find more in the Market.': '剧本提供了不同的英雄技能。 在市场中找到更多。',
    'Progress further to unlock this category.': '进一步解锁该类别。',
    'Bosses Defeated': 'Boss被击败了',
    'Change your game preferences and settings.': '改变你的游戏偏好和设置。',
    'Clear Saved Game Data': '清除保存的游戏数据',
    'Comitatus': '喜剧演员',
    'Complete guild orders to earn reputation and level up your guild.': '完成公会订单以赢得声望并升级您的公会。',
    'Feel free to check out our About & Crediting page or join us on Discord.': '随时查看我们的“关于＆鸣谢”页面或加入Discord。',
    'Import Game Data': '导入存档',
    'Import your own previously exported data or shared game data.': '导入您自己以前导出的存档数据或别人给你共享的游戏存档数据。',
    'If you plan on fighting in the shadows, this is the place to start.': '如果你计划在阴影中战斗，这是开始的地方。',
    'Mastering will remove material costs and grant higher rarity chances. Crafting more of a recipe will lower the mastery cost.': '精通技能将消除物质成本，并给予更高的稀有几率。制作更多的配方将降低精通成本。',
    'Eryn': '艾琳',
    'Oren': '奥伦',
    'Gillian': '吉莉安',
    'Smash': '粉碎',
    'Stilettos': '短剑',
    'Pyromania: A Love Story': '纵火狂：爱情故事',
    'Playbooks': '剧本',
    'Game Statistics': '游戏统计',
    'Herbie': '赫比',
    'Hero Equipment Upgrades': '英雄装备升级',
    'Tiara': '头饰',
    'Loyal Companion': '忠诚伴侣',
    'Named for the common technique of "Water Stabbing," which is the best way to catch a fish.': '得名于普通的“水刺”技术，这是最好的捕鱼方法。',
    'Some suggest that the original name is actually "This Is A Knife" -- they\'re wrong.': '有些人认为它最初的名字实际上是“这是一把刀”——他们错了。s',
    'Sure, a talking dog and a duck who refuses to wear pants is fine, but the weapon is breaking immersion.': '当然，一只会说话的狗和一只拒绝穿裤子的鸭子是没问题的，但这种武器正在打破沉浸感。',
    'Overall Progress': '整体进度',
    'Perks Purchased': '购买的福利',
    'Populating recipes...': '正在填充配方...',
    'Your overall game progress.': '您的整体游戏进度。',
    'Export Game Data': '导出游戏存档',
    'Craft': '制作',
    'Crash': '崩溃',
    'Hall of Milestones': '里程碑大厅',
    'Fusion Cabin': '融合小屋',
    'Adventure Areas': '冒险区域',
    'Select an area for your heroes to explore.': '选择一个区域让你的英雄去探索。',
    'Magical Synthesizer': '魔法合成器',
    'Aviation Association': '航空协会',
    'Trawled Treasures': '搜罗珍宝',
    'Adventure Enemy Party': '冒险敌方',
    'Adventure In Progress': '进行中的冒险',
    'Idle': '空闲',
    'Crafting Slots': '制作槽',
    'Clear Saved Game Data?': '清除游戏存档？',
    'Clear your saved game data from this browser? This action is irreversible.': '从这个浏览器清除你保存的游戏数据?这一操作是不可逆转的。',
    'Delete Game Data': '删除游戏存档',
    'Keep Game Data': '保留游戏存档',
    'Permanently delete your current saved game data. This action is irreversible.': '永久删除您当前保存的游戏数据。这一操作是不可逆转的。',
    'or delete your current save to start a new game.': '或删除当前存档以开始新游戏。',
    'Export Saved Game Data?': '导出保存的游戏存档？',
    'Export your current game data for sharing or importing at a later time.': '导出您当前的游戏数据以便以后共享或导入。',
    'Export your game data for sharing or use at a later time in another browser, computer or device. Copy the export string below for importing.': '导出您的游戏数据，以便以后在其他浏览器、计算机或设备中共享或使用。复制下面的导出字符串以便导入。',
    'Download as File': '下载存档文件',
    'Copy to Clipboard': '复制到剪贴板',
    'Import Saved Game Data?': '导入游戏存档？',
    'Import game data by inputting the export string and pressing the \'Import Save\' button.': '输入存档代码并按“导入存档”按钮导入游戏数据。',
    'Adjust your game preferences and settings. These settings will only be applied to this browser.': '调整你的游戏偏好和设置。这些设置将只应用于此浏览器。',
    'About & Crediting': '关于 & 鸣谢',
    'Choose whether tooltips are rendered when hovering over tooltip-enabled content.': '选择当鼠标悬停在启用工具提示的内容上时是否呈现工具提示。',
    'Designates where the notifications for various events (such as exceptional crafts) will appear.': '指定各种事件(如特殊的工艺品)的通知将出现的地方。',
    'Disabled': '禁用',
    'No Active Fortune': '没有活跃的财富',
    'Notification Location': '通知位置',
    'Game not available on this device': '游戏在此设备上不可用',
    'Tooltips': '工具提示',
    'Top-Center': '中上',
    'Top-Right': '右上',
    'Top-Left': '左上',
    'Bottom-Center': '中下',
    'Bottom-Left': '左下',
    'Bottom-Right': '右下',
    'Enabled': '启用',
    'Reset All Settings': '重置所有设置',
    'Reset your settings to default values for this browser only. This will reload the game but your progress will not be reset.': '仅将此浏览器的设置重置为默认值。 这将重新加载游戏，但您的进度不会被重置。',
    'Progress Tracker': '进度追踪器',
    'Join us on Discord': '在Discord上加入我们',
    'Available Guild Orders': '可用的公会订单',
    'Available Guild Sales': '可用公会销售',
    'Beat next boss to unlock!': '击败下一个Boss来解锁！',
    'Available Perks': '可用福利',
    'Unmastered Only': '只显示未精通',
    'Rewards': '奖励',
    'Mastered Only': '只显示已精通',
    'Just make sure you don\'t get sand in it.': '只是要确保不要把沙子弄进去。',
    'Hull': '船体',
    'Lakekeeper': '旁观者',
    'Lakur': '拉库尔',
    'Pullum': '吊坠',
    'Earthshaping and You': '塑造地球与你',
    'Amici': '埃米希',
    'Abandon Dungeon': '放弃地下城',
    'Gladio': '格拉迪欧',
    'Efficient Spells': '高效法术',
    'Dignity': '尊严',
    'Hut': '小屋',
    'Galoshes': '胶套鞋',
    'Helmut': '头盔',
    'Empty Slot': '空槽',
    'Stars': '之星',
    'Represents a worker for the guild.': '代表公会的一名工人。',
    'Zoe\'s Quest': '佐伊的任务',
    'hero is needed to assist with a potential divergence of timelines.  You don\'t have to turn off the red light, but getting pizza would be seen as a bonus.': '需要英雄来协助时间表的潜在分歧。 您不必关闭红灯，但拿披萨将被视为一种奖励。',
    'hero to help them with a problem.  They are suffering from a gas leak and report many popping noises.': '帮助他们解决问题的英雄。 他们正遭受煤气泄漏之苦，并报告许多爆裂声。',
    'Intense Purple Cuirass': '深紫色铠甲',
    'is hereby commissioned to rescue Sir Doogleberry from an ancient tomb with puzzle elements and a save system.': '被委任从一个带有谜题元素和一个保存系统的古墓中营救杜格贝里爵士。',
    'Select a quest for your heroes to partake in.': '选择一个任务让您的英雄参与。',
    'Sir Randolph Doogleberry': '伦道夫·杜格伯里爵士',
    'traveler to acquire cruise tickets for their northern team.  Don\'t let their promises go undelivered.': '旅行者为其北部团队获取游轮票。 不要辜负他们的诺言。',
    'Trawled Treasures desires a': '搜罗珍宝希望一个',
    '.  Head on over to the Steam Pipe Trunk Distribution Venue, and consider bringing them a muffin.': '。去蒸汽管道分配地点，考虑给他们带一个松饼。',
    'A neighboring distributor needs a champion with': '邻近的经销商需要一个冠军与',
    'Caeda, again.': '凯达，再次的。',
    'adventurer to bring them some milk.  They will pay handsomely to anyone who will travel to the wall and pick some up.': '冒险家给他们带点牛奶。他们会给任何到长城去买一些的人丰厚的报酬。',
    'Questing Locations': '搜寻地点',
    'Your overall progress throughout the game.': '您在整个游戏中的总体进度。',
    'Wizard College': '巫师学院',
    'The Milk Hole': '牛奶洞',
    'Steam Pipes': '蒸汽管道',
    'An adventurer with': '一个冒险家和',
    'Buckler': '圆盾',
    'Burning Sticks': '燃烧棒',
    'Caeda\'s Other Quest': '凯达的另一个任务',
    'Crown': '皇冠',
    'Cutlass': '弯刀',
    'Cruise Tickets': '邮轮船票',
    'Time Spent Offline': '离线时间',
    'Recipe Mastery': '配方精通',
    'Serpent Mail': '蛇形锁',
    'on Patreon': '在Patreon上',
    'Nal\'Dur\'s Diary': '杜尔的日记',
    'Adipem Pater': '阿迪彭·帕特',
    'Gold Earned': '获得黄金',
    'Requirements': '要求',
    'Strennus': '强度',
    'Moxie': '勇气',
    'Mindful': '强大的',
    'Maidens': '少女',
    'Quest Inactive': '任务未激活',
    'Offline Progression': '离线进度',
    'Here\'s what happened while you were offline.': '这是您离线时发生的情况。',
    'Chaos Theory': '混沌理论',
    'Arms Race': '军备竞赛',
    'Rain Fire': '火雨',
    'Rollin In The Deep': '罗林深处',
    'Start Fusion': '开始融合',
    'Song Of Life': '生命之歌',
    'Store in Bank': '存入银行',
    'Revenge': '复仇',
    'Revere has nothing to prove, because she knows the truth: she can do anything.': '里维尔有什么可以证明的，因为她知道真相：她可以做任何事情。',
    'Research new trinket recipes that can be crafted for gold.': '研究可以用黄金制作的新饰品配方。',
    'Reputation': '声望',
    'Shield Up': '完美护盾',
    'Notes': '日志',
    'patch notifications should work now': '补丁通知现在可以工作了',
    'Perks': '福利',
    'PERKS': '福利',
    'View Trinkets Recipes': '查看小饰品配方',
    'Used to level up guilds.': '用来升级公会。',
    'Your Inventory': '你的库存',
    'Your Available Heroes': '你可用的英雄',
    'This guild became expert crafters after studying shipwrecked valuables.': '这个行会在研究了海难中的贵重物品后，成为了手工艺专家。',
    'This hammer won\'t hurt your gear. ': '这把锤子不会损坏你的装备。',
    'Trinket Research': '饰品的研究',
    'Upgrade your equipment slots by 5% for each stat using Monster Trophies.': '使用怪物奖杯使你的装备槽每项属性提升5%。',
    'Use Essence to transform the stats on a piece of equipment.': '使用精华转换装备属性。',
    'Thief': '盗贼',
    'Third Time': '第三次',
    'Caeda\'s Quest': '凯达的任务',
    'Cedric\'s Quest': '塞德里克的任务',
    'Flip It And Reverse It': '翻转并反转它',
    'Slots': '插槽',
    'Revere\'s Quest': '里维尔的任务',
    'Secret Streams': '秘密流',
    'Mighty': '强大的',
    'The heroes you have selected for this adventure.': '你为这次冒险选择的英雄。',
    'The enemies you will battle in this adventure.': '你将在这次冒险中与之战斗的敌人。',
    'The nearby Wizard College is requesting a': '附近的巫师学院需要一个',
    'Alok\'s Quest': '阿洛克的任务',
    'Alok.': '阿洛克。',
    'champion to assist them in the shipment of rare Bird Arms.': '冠军去协助他们运送稀有鸟类武器。',
    'champion and a': '冠军和一个',
    'Delete Data': '删除数据',
    'Feverbreaker': '狂热者',
    'Grim\'s Quest': '格里姆的任务',
    'Quest Time': '任务时间',
    'Grogmar\'s Quest': '格罗格玛的任务',
    'A record of how far along into a run a boss was beaten.': '记录了打败一个Boss用了多久。',
    'A statistical overview of your game progression and accomplishments.': '你的游戏进度和成就的统计概述。',
    'Defiant Targe': '挑衅的圆盾',
    'Fortune Teller': '预言家',
    'Foxy Slippers': '狐狸拖鞋',
    'Generous Blocker': '慷慨的阻止者',
    'Green Bay Beret': '绿湾贝雷帽',
    'Inpulsa Sciurus': '冲击松鼠',
    'Magicae Criceta': '魔术师克里塞塔',
    'Jay Walkers': '杰·沃克',
    'Gelata Eros': '神仙鱼',
    'Upgrade': '升级',
    'View Knives Recipes': '查看刀具配方',
    'View Masks Recipes': '查看面具配方',
    'View Staves Recipes': '查看权杖配方',
    'View Swords Recipes': '查看剑配方',
    'Wounded Target': '受伤目标',
    'Swipe': '击打',
    'Select Your Hero Trinket': '选择你的英雄饰品',
    'Select Your Hero Equipment': '选择你的英雄装备',
    'Outbreak': '爆发',
    'Caddish Cactus': '下流的仙人掌',
    'Cinder Phoenix': '灰烬凤凰',
    'Boss Dungeon Not Available': 'Boss地下城不可用',
    'Distribution Djinn': '巨灵分布',
    'Larry Jr': '小拉里',
    'Lich King Larry': '巫妖王拉里',
    'Loathing Oak': '厌恶橡树',
    'Monkey Knife Fight': '猴子刀战',
    'Paintbrush Knight': '画笔骑士',
    'Rechallenge Boss': '再战Boss',
    'Start Boss Fight': '初战Boss',
    'Johnny Jaw': '约翰尼·乔',
    'Maximush': '最大限度',
    'Minimush': '最低限度',
    'Pink Ooze': '粉红色软泥',
    'Tepid Turtle': '温热龟',
    'The Avian Association seeks a': '鸟类协会寻求一个',
    'Dwarf Minor': '小矮人',
    'Dwarf Sentry': '矮人哨兵',
    'Elf Adventurer': '精灵冒险家',
    'Green Ooze': '绿色软泥',
    'Empty Party Slot': '空方槽',
    'A special quest for Grim.  Grim will need help from Titus.': '格里姆的特殊任务。格里姆需要提图斯的帮助。',
    'A special quest for Grogmar.  Grogmar will need help from Zoe.': '格罗格玛的特殊任务。格格玛需要佐伊的帮助。',
    'A special quest for Revere.  Revere will need help from Neve.': '里维尔特殊任务。里维尔需要尼芙的帮助。',
    'Levels': '等级',
    'Notifications': '通知',
    'Notification Duration': '通知持续时间',
    'General': '常规',
    'End Session Confirmation': '结束会话确认',
    'A list of all of your accomplishments and progress.': '一个清单，列出你所有的成就和进步。',
    'Add to Inventory': '增加库存',
    'Adds another slot to your Fusion Cabin.': '为你的融合小屋增加了另一个插槽。',
    'Adds new capabilities to the Magical Synthesizer.': '为魔法合成器增加了新功能。',
    'Allows you to fight old bosses in the Boss Realm. They scale in difficulty, and reward valuable trophies!': '允许你在Boss王国与旧Boss战斗。它们按照困难程度掉落有价值的奖杯!',
    'Alok\'s Other Quest': '阿洛克的其他任务',
    'An entire vault of safety deposit boxes, just for you.': '整个金库的保险箱都是为你准备的',
    'Assign Fusion': '分配融合',
    'Assign Item': '分配物品',
    'Assign Offering': '分配祭奠品',
    'Assign Smith': '分配锻造',
    'Auto Sell': '自动出售',
    'Bank Storage': '银行存储',
    'Become the master alchemist you\'ve always wanted to be.': '成为你一直想成为的炼金大师。',
    'Beorn\'s Quest': '贝恩的任务',
    'Birds of A Feather': '一丘之貉',
    'Blood Bond': '血之连接',
    'Bubbles': '泡泡',
    'Bumbling Bee': '大黄蜂',
    'Can I Be Your Plus One': '我可以是你的唯一吗',
    'Can I Be Your Plus Two': '我可以是你的唯二吗',
    'Cold Confidence': '寒冷的信心',
    'Collect Fusion': '收集融合',
    'Complete Research': '完成研究',
    'Creepy Alien': '令人毛骨悚然的外星人',
    'Crusty Crab': '硬壳螃蟹',
    'currency used for purchases.': '用于购买的货币。',
    'Desynthesis': '分解',
    'Did You Lose Weight': '你减肥了吗',
    'Discord': 'Discord',   
    'Dusty Alien': '灰暗的外星人',
    'Elf Scout': '精灵斥候',
    'Empty Forge Slot': '空锻造槽',
    'Empty Fusion Slot': '空熔合槽',
    'Epic': '史诗',
    'Epic Fusion': '史诗级融合',
    'Fortune Offerings Available': '可利用的财富',
    'Fourth Slot': '第四槽',
    'Get your Fix': '去修理一下',
    'Harness the magical arts to transform your equipment.': '利用魔法来改造你的装备。',
    'Having A Ball': '举行舞会',
    'hero and a mercenary with': '英雄和雇佣兵',
    'Heroes\' Inventory': '英雄目录',
    'Hopefully she won\'t disappear.': '希望她不会消失。',
    'Hot Tin Roof': '热铁皮屋顶',
    'How it works': '工作原理',
    'It\'s an artifact finding mission.': '这是一个手工艺品发现任务。',
    'Items Available for Fusion': '可用于融合的项目',
    'Items Available for Synthesizer': '可以用于合成器的项目。',
    'Items in your inventory that can be used in the Synthesizer.': '目录中可以用于合成器的项目。',
    'Items in your inventory that you can upgrade.': '目录中可以升级的项目。',
    'Items you currently have in your inventory.': '您当前目录中的项目。',
    'Items you currently have stored in the bank.': '您当前存储在银行中的项目。',
    'Items your heroes have equipped that you can upgrade.': '英雄装备的物品可以升级。',
    'Jackslot': '杰克斯洛',
    'Kale is Gross': '甘蓝是灰色的',
    'Krakoptopus': '克拉科普托普斯',
    'Marked Target': '标记的目标',
    'More To Store': '更多要存储的',
    'Neve\'s Quest': '尼芙的任务',
    'Opens up the Questing feature.  Your heroes might be happy to have new things to do.': '打开任务功能。你的英雄们也许会很高兴有新的事情要做。',
    'Over Engineered': '过度设计',
    'Receive special Essence in exchange for lowering the rarity of a piece of equipment by one tier.': '获得特殊精髓，换取一件装备的稀有程度降低一层。',
    'Research Cost': '研究费用',
    'Rockfall': '落石',
    'Safety Not Guaranteed': '安全没有保障',
    'Sesame Seed Money': '芝麻钱',
    'Song Of Strength': '力量之歌',
    'Sort Bank Storage': '分类库存储',
    'The amount of time needed to complete this quest.': '完成这个任务所需的时间。',
    'The amount of time needed to craft this recipe.': '制作这个配方所需的时间。',
    'Titus\'s Quest': '提图斯的任务',
    'to go back in time with me.  This is not a joke.  I have only done this once before.': '和我一起回到过去。这不是开玩笑。我以前只做过一次。',
    'To The Chaos Gate!': '去混沌之门！',
    'Troy\'s Quest': '特洛伊的任务',
    'Unlock a special quest, for Grim and a friend.': '开启一个特殊的任务，为格里姆和一个朋友。',
    'Unlock a special quest, just for Alok, again.': '再次解锁一个特殊任务，只为阿洛克。',
    'Unlock a special quest, just for Caeda, again.': '再次解锁一个特殊任务，只为凯达。',
    'Unlock the Boss Realm.  Slay these difficult enemies to unlock more content.': '开启Boss王国。杀死这些困难的敌人，以解锁更多的内容。',
    'Unlocked Tinker Recipes': '解锁修补程序配方',
    'Unlocks access to the Aviation Association Crafting Guild.  They specialize in Weaponmaking.': '解锁对航空协会工艺协会的访问。他们专门制造武器。',
    'Unlocks Eryn, a worker for Aviation Association.': '解锁埃尔恩，一个航空协会的工人。',
    'Unlocks Grogmar, the trustworthy sniper.': '解锁格罗格玛，值得信赖的狙击手。',
    'Unlocks Herbie, a worker for Aviation Association.': '解锁赫比，一个航空协会的工人。',
    'Unlocks Lakur, a worker for Aviation Association.': '解锁拉库尔，一个航空协会的工人。',
    'Unlocks the Fortune Teller, to increase exceptional craft odds.': '解锁算命师，增加特殊工艺几率。',
    'Unlocks the Magical Synthesizer, capable of interacting with the magical properties of items.': '解锁魔法合成器，可以与物品的魔法属性进行交互。',
    'Unlocks Titus, the nefarious warlock.': '解锁提图斯，邪恶的术士。',
    'Unlocks your first Dungeon, the Groovy Grove, where you can collect rare crafting materials.': '解锁你的第一个地下城，奇妙的小树林，在那里你可以收集稀有的制作材料。',
    'Use three of the same item to fuse into higher rarity.': '使用三个相同的物品融合成更稀有的物品。',
    'Wanted: A': '悬赏级别：A',
    'Wiggle Worm': '摆动蠕虫',
    'You can offer up the following items for a fortune.': '你可以出高价出售下列物品。',
    'You Need A Break': '你需要休息',
    'You Sound Familiar': '你听起来很熟悉',
    'Your available Trinket recipes. They are always crafted at Epic rarity!': '你可用的小饰品配方。它们总是以史诗稀有级别被制作出来！',
    'Your Future Is Green': '你的未来是绿色的',
    'Lambug\'s Other Quest': '林虫的另一个任务',
    'Lambug\'s Quest': '林虫的任务',
    'Milestone Markers': '里程碑标记',
    'Neve\'s Other Quest': '尼芙',
    'Stinky Divers': '臭潜水员',
    'The Aviation Association': '航空协会',
    'The Green Guard': '绿卫队',
    'The Museum': '博物馆',
    'Titus\'s Other Quest': '提图斯的其他任务',
    'Troy\'s Other Quest': '特洛伊的其他任务',
    'Unlock a special quest, for Grogmar and a friend.': '解锁一个特殊任务，为格罗格玛和一个朋友',
    'Unlock a special quest, for Revere and a friend.': '解锁一个特殊任务，为里维尔和一个朋友',
    'Unlock a special quest, just for Alok.': '解锁一个特殊的任务，仅针对阿洛克。',
    'Unlock a special quest, just for Beorn.': '解锁一个特殊的任务，仅针对贝恩。',
    'Unlock a special quest, just for Beorn, again.': '再次解锁一个特殊的任务，仅针对贝恩。',
    'Unlock a special quest, just for Cedric, again.': '再次解锁一个特殊的任务，仅针对塞德里克。',
    'Unlock a special quest, just for Lambug, again.': '再次解锁一个特殊的任务，仅针对林虫。',
    'Unlock a special quest, just for Neve, again.': '再次解锁一个特殊的任务，仅针对尼芙。',
    'Unlock a special quest, just for Titus, again.': '再次解锁一个特殊的任务，仅针对提图斯。',
    'Unlock a special quest, just for Troy, again.': '再次解锁一个特殊的任务，仅针对特洛伊。',
    'Unlock a special quest, just for Caeda.': '解锁一个特殊的任务，仅针对凯达。',
    'Unlock a special quest, just for Cedric.': '解锁一个特殊的任务，仅针对塞德里克。',
    'Unlock a special quest, just for Grim.': '解锁一个特殊的任务，仅针对格里姆。',
    'Unlock a special quest, just for Lambug.': '解锁一个特殊的任务，仅针对林虫。',
    'Unlock a special quest, just for Neve.': '解锁一个特殊的任务，仅针对尼芙。',
    'Unlock a special quest, just for Titus.': '解锁一个特殊的任务，仅针对提图斯。',
    'Unlock a special quest, just for Troy.': '解锁一个特殊的任务，仅针对特洛伊。',
    'Unlock a special quest, just for Zoe.': '解锁一个特殊的任务，仅针对佐伊。',
    'Unlocks ability to Auto Sell items.  You can enable this ability directly on your crafting slots.': '解锁自动出售物品的能力。 您可以直接在制作插槽中启用此功能。',
    'Unlocks access to the Green Guard Crafting Guild.  They are experts in Defensive goods.': '解锁对绿色警卫队制作公会的访问权限。 他们是国防商品专家。',
    'Unlocks access to the Guild Feature and the Cat\'s Meow guild.  Work on those Guild Orders.': '解锁对公会功能和猫喵喵公会的访问。 按照这些公会命令工作。',
    'Unlocks access to the Trawled Treasures Crafting Guild, home of mysterious Valuables.': '解锁进入搜罗珍宝手工行会的大门，这是神秘贵重物品的故乡。',
    'Unlocks Alok, the crafty inspirer.': '解锁阿洛克，狡猾的启发者。',
    'Unlocks Beorn, the noble warrior.  Don\'t forget to give him a sword.': '解锁高贵的战士贝恩。 别忘了给他一把剑。',
    'Unlocks Caeda, the skilled tactician.': '解锁凯达，熟练的战术家。',
    'Unlocks Cedric, the dutiful protector.': '解锁忠实的保护者塞德里克。',
    'Unlocks Crash, a worker for Green Guard.': '解锁崩溃，绿卫队的一名工人。',
    'Unlocks extra levels in all of your dungeons.  Each time you beat a boss, new dungeon levels will open up.': '解锁所有地下城中的额外关卡。 每次您击败Boss时，都会解锁新的地下城级别。',
    'Unlocks Gilda, a worker for Trawled Treasures.': '解锁搜罗珍宝工人吉尔达。',
    'Unlocks Gilfred, a worker for Trawled Treasures.': '解锁搜罗珍宝工人吉尔弗雷德。',
    'Unlocks Gillian, a worker for Trawled Treasures.': '解锁搜罗珍宝工人吉莉安。',
    'With Less Ads': '减少广告',
    'You Can Bank On It': '你可以依靠它',
    'Unlocks Zoe, the cunning sorcerer.': '解锁狡猾的巫师佐伊。',
    'Unlocks Grim, the bloodthirsty barbarian.': '解锁嗜血的野蛮人格里姆。',
    'Unlocks Lambug, the ferocious attacker.': '解锁凶猛的攻击者林虫。',
    'Unlocks Neve, the focused mage.  Now you can farm all dungeons at the same time.': '解锁专注的法师尼芙。 现在，您可以同时种植所有地下城。',
    'Unlocks Renae, a worker for The Cat\'s Meow.': '解锁雷那，猫喵喵的一名工人。',
    'Unlocks Revere, your very first Adventurer! Make sure to give her good equipment.': '解锁里维尔，您的第一个冒险家！ 确保给她好的装备。',
    'Unlocks Smash, a worker for Green Guard.': '解锁粉碎，绿卫队的一名工人。',
    'Unlocks Squeaks, a worker for The Cat\'s Meow.': '解锁吱吱，猫喵喵的一名工人。',
    'Unlocks Tawny, a worker for The Cat\'s Meow.': '解锁茶色，猫喵喵的一名工人。',
    'Unlocks the Bank, so you can store your stuff.': '解锁银行，以便您可以存储自己的东西。',
    'Unlocks the Creepy Crag dungeon, home of the rare crafting material, Crystals.': '解锁令人毛骨悚然的岩壁地下城，这是稀有的手工制作材料水晶的所在地。',
    'Unlocks the fifth Crafting Slot.': '解锁第五个工艺插槽。',
    'Unlocks the fourth Crafting Slot.': '解锁第四个工艺插槽。',
    'Unlocks the third Crafting Slot.': '解锁第三个工艺插槽。',
    'Unlocks the Forge, so you can improve item stats.': '解锁锻造，因此您可以提升物品属性。',
    'Unlocks the Fusion Cabin, so you can increase item quality.': '解锁融合小屋，因此您可以提高物品质量。',
    'Unlocks the Hall of Milestones.  This will tell you how far you are in the game.': '解锁里程碑大厅。 这将告诉您您在游戏中的距离。',
    'Unlocks the Museum building.  Hand over equipment to improve your crafting!': '解锁博物馆建筑。 交出装备以提升工艺！',
    'Unlocks the second Crafting Slot.  Now you can craft from two different Guilds at the same time.': '解锁第二个手工插槽。 现在，您可以同时从两个不同的行会制作手工艺品。',
    'Unlocks the Spooky Spot dungeon, home of the Slime crafting material.': '解锁史莱姆制作材料所在地幽灵点地牢。',
    'Unlocks the Tinker Hut.  Get to work on those trinkets.': '解锁修补匠小屋。 开始在那些小饰品上工作。',
    'Unlocks Titan, a worker for Green Guard.': '解锁泰坦，绿色卫队的一名工人。',
    'Unlocks Troy, the adept healer.': '解锁特洛伊，娴熟的医生。',
    'Increases the storage capability of the Bank.': '增加银行的存储能力。',
    'A record of how far along into a run a boss was defeated.': '记录了一个Boss被打败的时间。',
    'Adds an additional Fortune Teller option.': '添加一个附加的算命先生选项。',
    'Beorn\'s Other Quest': '贝恩的其他任务',
    'Blathering On': '吹牛',
    'Boss Battle': 'Boss之战',
    'Can I Be Your Plus Three': '我可以是你的唯三吗',
    'Cedric\'s Other Quest': '塞德里克的其他任务',
    'Crystal Ballerina': '水晶芭蕾',
    'Feline Fine': '猫科动物',
    'Grim\'s Other Quest': '格里姆的其它任务',
    'The number of additional perks left in this line.': '此行中剩余的额外福利数。',
    'Additional Perks Remaining': '剩余的额外福利',
    'In Inventory': '库存中',
    'Amount currently in your inventory.': '当前库存中的数量。',
    'The amount of gold this recipe is worth.': '此配方值得的黄金量。',
    'Titan often finds himself moderating disputes in the shop.': '泰坦经常在商店里发现自己在缓和纠纷。',
    'Crash relies on reputable traders for raw materials.': '崩溃依赖信誉良好的贸易商提供原材料。',
    'Eryn carefully chooses which materials to use.': '艾琳会仔细选择要使用的材料。',
    'Francis wants to be the very best, the best that ever was.': '弗朗西斯希望成为有史以来最好的。',
    'Gilbert is an excellent understudy with a bright future.': '吉尔伯特是出色的研究者，前景光明。',
    'Gilda doesn\'t enjoy her job, but her bills get paid on time.': '吉尔达不喜欢她的工作，但她的账单必须按时支付。',
    'Gilfred hopes to become a designer one day.': '吉尔弗雷德希望有一天成为一名设计师。',
    'Gillian has a underground black market supplier.': '吉莉安拥有地下黑市供应商。',
    'Herbie is a fledgling botanist in his spare time.': '赫比在业余时间是一位刚起步的植物学家。',
    'Lakur is a skilled hunter and is proud to use her own products.': '拉库尔是一位熟练的猎人，并为使用自己的产品感到自豪。',
    'Oren comes from a long line of crafters.': '奥伦来自众多手工艺者。',
    'Renae was taught by her mother to produce high quality goods.': '雷娜的母亲教她生产高品质的商品。',
    'Slime': '粘液',
    'Smash has excellent attention to detail, and it shows.': '粉碎非常注重细节，因此很明显。',
    'Squeaks is shy around new customers, but is very loyal.': '吱吱对新客户害羞，但非常忠诚。',
    'Tawny secretly moonlights as a dancer after business hours.': '营业时间后，黄褐色偷偷地扮演舞者。',
    'Time': '时间',
    'Tiny is a hard-working student, hoping to learn all he can.': '蒂妮是位勤奋的学生，希望能学到一切。',
    'Who Says I\'m In': '谁说我在',
    'The Green Guard of the Rapid Chi Orchard request two individuals: one with': '拉普奇果园的绿卫兵要求两个人：一个拥有',
    'Might': '强大',
    ', and another with': '，另一个拥有',
    '.  Hacking experience a plus, but not required.': '。 有一定的黑客经验，但不是必须的。',
    'Attack': '攻击',
    'Beorn applies Phalanx to his allies. While Phalanx is active on an ally, it will transfer 25% of the next loss of health to Beorn.': '贝奥恩对他的盟友使用方阵。当方阵在一个盟友身上活动时，它会将下次损失的生命值的25%转移给贝奥恩。',
    'Beorn gains Reinforce.  Reinforce reduces damage taken from incoming attacks by 50%.': '贝恩获得增强。 加强可将受到的攻击造成的伤害降低50％。',
    'Beorn gains Riposte.  Riposte negates the next incoming attack.  When consumed, Beorn will counterattack for': '贝恩获得还击。 还击免疫受到的下一次攻击。 消耗掉后，贝恩会还击',
    'Deal': '造成',
    'One popular urban legend mentions that this blade is involved in fowl play.': '一个流行的都市传说提到，这把剑涉及到家禽游戏。',
    'Phalanx': '阵型',
    'Reinforce': '加强',
    'Riposte': '还击',
    'Stay Behind Me': '待在我后面',
    'to frontmost enemy.': '到最前面的敌人。',
    'Cannot Swap Playbook': '不能互换剧本',
    'Epic Rarity': '史诗稀有',
    'Max Level': '最高级',
    'rarity.': '稀有度.',
    'This item is of': '这个物品是',
    'You cannot swap playbooks while the hero is on an adventure.': '当英雄冒险时，您不能交换剧本。',
    'by 10%, and reduces his max HP by 10%.': '10％，并使其最大生命值降低10％。',
    'Cedric gains Corruption.  Corruption increases Cedric\'s': '塞德里克获得腐败。 腐败加剧了塞德里克的',
    'Cedric gains Purity.  Purity increases max HP by': '塞德里克获得纯净。 纯净将最大HP增加了',
    'Cedric gains Righteousness.  While Righteousness is active, enemy attacks will be focused on Cedric.': '塞德里克获得公义。当公义激活时，敌人的攻击将集中在塞德里克身上。',
    'Corruption': '腐败',
    'Fall From Grace': '失宠',
    'Forge Enhancement': '锻造强化',
    'Grim deals': '格里姆造成',
    'Purity': '纯净',
    'Remove Slotted Equipment': '卸下插槽装备',
    'Righteousness': '公义',
    'The enhancement level of this item. You can enhance items in the Forge building.': '此物品的强化级别。 您可以在锻造建筑物中强化物品。',
    'This will remove the currently equipped item on this slot and return it to your inventory.': '这将删除此插槽上当前装备的物品，并将其放进您的库存。',
    'to the frontmost enemy and Grim loses HP equal to 15% of his max HP.': '面对最前面的敌人，格里姆会损失相当于其最大生命值15%的生命值。',
    'to the frontmost enemy.  If the enemy has Necrosis, Grim will heal himself for': '向最前方的敌人进攻。如果敌人已经坏死，格里姆就会为自己疗伤',
    'to the two frontmost enemies and Grim loses HP equal to 15% of his max HP.': '面对最前面的两个敌人，格里姆损失的生命值等于其最大生命值的15%。',
    'Blood Cleave': '血劈',
    'Bloodbath': '血浴',
    'per stack to enemies on their turn. Titus will not sap Grim.': '在敌人的回合中给予每一堆叠。提图斯不会吸取格里姆。',
    'Regen': '回复',
    'Rejuvenate': '复原',
    'Requiem': '安魂曲',
    'Restore': '恢复',
    'Snipe': '狙击',
    'Snowstorm': '暴风雪',
    'Song Of Pain': '痛苦之歌',
    'Strike': '打击',
    'Zoe deals': '佐伊造成',
    'Titus applies Necrosis to all enemies and allies. Necrosis deals': '提图斯对所有敌人和盟友使用了坏死。 坏死造成了',
    'Necrosis': '坏死',
    'Titus saps life energy from the ally behind him to apply Necrosis on his enemy counterpart. Necrosis deals': '提图斯从他身后的盟友那里吸取生命力，将坏死作用在他的敌人身上。坏死造成',
    'Titus saps life energy from the ally in front of him to apply Necrosis on his enemy counterpart. Necrosis deals': '提图斯从他前面的盟友身上吸取生命力，以使对手坏死。坏死造成',
    'to all enemies and applies Chilled.': '所有敌人生效，并施加冰冻。',
    'to all enemies and applies Scorch.  Scorch deals 10': '对所有敌人施加灼烧，灼烧造成',
    'to enemies on their turn.': '给敌人在他们的回合',
    'to the frontmost enemy and applies Scorch.  Scorch deals': '对最前面的敌人施加灼烧，灼烧造成',
    'Scorch': '灼烧',
    'to the frontmost enemy and then gains Tired.  Tired reduces damage done by Overexertion by 30% per stack.': '到最前面的敌人，然后获得疲倦。疲倦每堆叠减少30%过度消耗造成的伤害。',
    'to the lowest HP enemy.  If that enemy is below 50% health, Grogmar deals': '给最低生命值的敌人。如果敌人的生命值低于50%，格罗格玛会出手',
    'to the third enemy.  If they are Scorched, Grogmar deals': '给第三个敌人。如果他们被烧焦了，格罗格玛造成',
    'to the two frontmost enemies.': '给两个最前面的敌人。',
    'Troy applies Regen to the frontmost ally.  Regen heals for': '特洛伊将回复应用于最前面的盟友。 恢复生命值',
    'Troy heals all allies for': '特洛伊可以治疗所有盟友',
    'Troy heals the ally missing the most HP for': '特洛伊治愈失去最多生命值的盟友',
    'View Armor Recipes': '查看盔甲配方',
    'View Belts Recipes': '查看腰带配方',
    'View Cloaks Recipes': '查看披风配方',
    'View Gauntlets Recipes': '查看护手配方',
    'View Gloves Recipes': '查看手套配方',
    'View Hats Recipes': '查看帽子配方',
    'View Helmets Recipes': '查看头盔配方',
    'View Pendants Recipes': '查看吊坠配方',
    'View Rings Recipes': '查看戒指配方',
    'View Shields Recipes': '查看盾牌配方',
    'View Shoes Recipes': '查看鞋子配方',
    'View Thrown Recipes': '查看投掷武器配方',
    'View Tomes Recipes': '查看书籍配方',
    'View Vests Recipes': '查看背心配方',
    'Waning Blows': '减弱打击',
    'Alok applies Madrigal to all allies. Madrigal increases Power by': '阿洛克对所有的盟友施以情歌。 情歌增加力量',
    'Alok applies Paeon to all allies.  Paeon increases max HP by': '阿洛克将诗歌应用于所有盟友。 诗歌将最大生命值提高',
    'Madrigal': '情歌',
    'Paeon': '诗歌',
    'Alok applies Requiem to all enemies. Requiem doubles damage taken for the next attack received.': '阿洛克将安魂曲应用于所有敌人。 安魂曲使下一次受到的伤害加倍。',
    'and applies Chilled.  If they are already Chilled,  this attack does': '并应用冰冻。 如果他们已经被冰冻，则此攻击会',
    'Blood Thrust': '推宫换血',
    'Bulls Eye': '靶心',
    'Caeda applies Marked to the fourth enemy.  Allies will focus their attacks on marked targets.': '凯达标记第四个敌人。盟军将集中攻击已标记的目标。',
    'Caeda applies Marked to the second enemy.  Allies will focus their attacks on marked targets.': '凯达标记第二个敌人。盟军将集中攻击已标记的目标。',
    'Caeda applies Marked to the third enemy.  Allies will focus their attacks on marked targets.': '凯达标记第三个敌人。盟军将集中攻击已标记的目标。',
    'Cleave': '劈开',
    'Cold As Ice': '冷如冰',
    'Cold Cuts': '冷切',
    'Conflagrate': '燃烧',
    'Dead Center': '死点',
    'Decay': '衰变',
    'Decompose': '分解',
    'Deep Freeze': '深度冻结',
    'Direct Hit': '直接命中',
    'Disintegrate': '瓦解',
    'Double Tap': '双击',
    'Flare': '闪光',
    'instead and removes Scorched.': '而是去除烧焦。',
    'instead.': '代替。',
    'Lambug deals': '林虫造成',
    'Light Connection': '光之连接',
    'Meteor': '流星',
    'Mind': '精神',
    'Neve attacks the frontmost enemy for': '尼芙攻击最前面的敌人',
    'Neve becomes immune to all damage until her next turn.': '尼芙直到下一回合都对所有伤害免疫。',
    'Neve deals': '尼芙造成',
    'on their turn.': '在他们的回合。',
    'Overexertion': '过劳',
    'Pandemic': '瘟疫',
    'per stack to enemies on their turn. Titus and Grim will not be affected.': '每一堆叠给予敌人在他们的回合。提图斯和格里姆不会受到影响。',
    'Revere deals': '里维尔造成',
    'to the frontmost enemy twice.': '向最前面的敌人进攻两次。',
    'to the second enemy.  If they are Chilled, Revere deals': '对第二个敌人。如果他们被冰冻，里维尔造成',
    'You have crafted a good rarity The Mind Cap!': '您精心制作了一个稀有的精神帽！',
    'Bee': '蜜蜂',
    'Parasite': '寄生虫',
    'Wasp': '黄蜂',
    'Worm': '蠕虫',
    'Blue': '蓝色',
    'Boss Defeats': 'Boss被击败',
    'Cobra': '眼镜蛇',
    'Peach': '桃色',
    'Clear': '明亮',
    'Crystal': '水晶',
    'Construct Building': '建造建筑物',
    'Emerald': '翠绿',
    'Ginger': '淡赤黄色',
    'Go to Inventory': '前往库存',
    'Good Fusion': '不错的融合',
    'Good The Mind Cap Crafted!': '精心制作的精神帽！',
    'Green': '绿色',
    'Hero Added To Party': '英雄加入团队',
    'Indigo': '靛青',
    'Indigo Slime Cost Removed': '消除了靛蓝史莱姆的费用',
    'Lightning Crystal': '闪电水晶',
    'Mastering this recipe has removed this material cost.': '精通此配方已消除了这种材料成本。',
    'Obtained via Desynthesis.': '通过分解合成获得。',
    'Psychic Crystal': '通灵水晶',
    'Purple': '紫色',
    'Rat': '老鼠',
    'Scorpion': '蝎子',
    'Spider': '蜘蛛',
    'Stinky': '臭的',
    'Synthesizer Setting': '合成器设置',
    'The amount of times you have defeated this boss.': '您击败该Boss的次数。',
    'This hero is already assigned to your party.': '该英雄已经分配到您的队伍。',
    'Unlock this building by crafting the recipe below.': '通过制作以下配方来解锁这座建筑物。',
    'View Hero Playbooks': '查看英雄剧本',
    'Common': '普通',
    'Common Rarity': '常见的稀有度',
    'Life': '生命',
    'Life Crystal': '生命水晶',
    'View your contribution details for each line.': '查看每一行的贡献细节。',
    'You have reached the current maximum guild level.': '您已经达到当前公会的最高等级。',
    'Your Questing Party': '你的任务团队',
    'Zielony': '朱丽娜',
    'Available Fortune Slots': '可用的财富插槽',
    'Contribute to the Museum': '为博物馆做贡献',
    'Czerwony': '切尔沃尼',
    'Donate': '捐赠',
    'Donate your items to earn crafting rewards.': '捐赠您的物品以获得手工艺品奖励。',
    'Goblin King': '地精王',
    'Let us know if you have items to donate.': '让我们知道您是否有要捐赠的物品。',
    'Niebieski': '涅别斯基',
    'Quest In Progress': '进行中的任务',
    'Recipe Lines': '配方线',
    'Select the heroes to send on this quest.': '选择要发送的英雄。',
    'Start Quest': '开始任务',
    'Synthesis': '合成',
    'The heroes you have selected for this quest.': '您为此任务选择的英雄。',
    'The number of fortune slots you have available for offerings.': '您可用于提供的财富插槽数量。',
    'There are no more recipes available to purchase.': '没有更多可供购买的配方。',
    'Enemy': '敌人',
    'Ice Crystal': '冰之水晶',
    'Great Fusion': '大师级融合',
    'Femur Fred': '费莫尔·弗雷德',
    'Elf Mender': '精灵治愈者',
    'Dwarf Magus': '矮人魔导士',
    'Quest Succeeded': '任务成功',
    'Smokie': '烟鬼',
    'Storm Crystal': '风暴水晶',
    'Shop Order': '商店订单',
    'Shop Orders': '商店订单',
    'Shop Recipes': '商店配方',
    'Sneaky Sneakers': '薄底帆布鞋',
    'Submitting Order': '提交订单',
    'Vested Interest': '既得利益',
    'Weapon Expertise': '武器专长',
    'Weaponmaker': '武器制造者',
    'Cloaking Devices': '隐形装置',
    'Completing shop orders allows you to gain new crafting recipes.': '完成车间订单可以使您获得新的工艺配方。',
    'Defeat the next boss to unlock more recipes.': '打败下一个Boss以解锁更多配方。',
    'Dry Clean Only': '只能干洗',
    'Get Your Fix"': '解决问题',
    'Gloves In Hand': '手套在手',
    'I Study The Blade': '我研究刀锋',
    'Homes For Tomes': '书屋',
    'Jeweler': '珠宝商',
    'Lapidarical Knowledge': '宗教知识',
    'Mask Work': '面具的工作',
    'Mastering recipes provides you with bonuses such as no material cost and higher rarity chances.': '掌握配方可以为你提供额外的奖励，比如无物质消耗和更高的稀有几率。',
    'Mastery': '精通',
    'More Info': '更多信息',
    'Merchant': '商人',
    'More Shop Orders': '更多的商店订单',
    'Penchant For Pendants': '吊坠附魔',
    'Potential Submittals': '潜在的屈服',
    'Run The Gauntlets': '运行长手套',
    'Scrapbooking...': '剪贴簿...',
    'Select a recipe to unlock and learn permanently.': '选择要解锁的配方并永久学习。',
    'Get Your Fix': '解决问题',
    'Market Guardian': '市场卫士',
    'Expeditions': '探险',
    'Expedition Parties': '探险队',
    'Perform expeditions for gold and other rewards': '进行探险以获得金币和其他奖励',
    'Store Champion': '商店冠军',
    'This hammer won\'t hurt your gear.': '这把锤子不会砸伤你的装备。',
    'You currently have no items available to fuse.': '您目前没有可用的物品可以融合。',
    'Create new Expedition party': '建立新的探险队',
    'Current parties out on expeditions.': '当前队伍已经派出探险了。',
    'Bazaar Gallant': '市场义卖',
    'Inventory items usable in the Synthesizer.': '合成器中可用的库存物品。',
    'Jeweler Worker': '珠宝工人',
    'Enable': '启用',
    'Receive special Essence in exchange for lowering the rarity of a piece of equipment to common.': '将一件装备的稀缺性降低到普通，获得特殊精华。',
    'Remaining': '剩余',
    'Synthesizer Boost': '合成器提升',
    'Specific workers are used in crafting and allocated automatically': '特定的工人被用于制作和自动分配',
    'Caeda has heard a rumor that a powerful new skill can be learned at the Snake Hole Lounge.': '凯达听说在蛇洞酒吧可以学到一种强大的新技能。',
    'Cannot Do Quest': '不能做任务',
    'Create or start an expedition party.': '创建或开始一个探险队。',
    'Expedition Party Creation': '探险队创建',
    'Hero Already Adventuring': '英雄已经冒险',
    'Neve is looking for answers about her past.  Maybe the Snake Hole is a good place to start?': '妮芙正在寻找关于她过去的答案。也许蛇洞是个不错的起点?',
    'One of Beorn\'s retired guard buddies has some information.  Seek them out at the Snake Hole.': '贝奥恩的一个退休狱友有一些消息。到蛇洞去找他们。',
    'One or more heroes are not available. Remove them from adventuring or other expeditions.': '一个或多个英雄不可用。将他们从冒险或其他探险中移除。',
    'Quests available for your heroes to embark on.': '你的英雄可以开始自己的任务。',
    'There may be remnants of an healing tonic at the Snake Hole.  Send Troy and friends to investigate.': '蛇洞里可能有残余的补药。派特洛伊和他的朋友去调查。',
    'Start Expedition': '开始探险',
    'This hero is already on another adventure.': '这位英雄已经踏上了另一段冒险之旅。',
    'A simple protective covering.': '一个简单的防护罩。',
    'Your Expedition Party': '你的探险队',
    'Assign heroes to embark on expeditions.': '指派英雄出发探险。',
    'Available Quests': '可用任务',
    'Bank Storage Sorting': '银行存储分类',
    'Check out the low calorie version -- Hard To Believe This Isn\'t A Butter Knife.': '看看低卡路里的版本——很难相信这不是黄油刀。',
    'Cogsmith Worker': '锻工',
    'Even the mighty oak starts as a simple acorn.': '即使是伟大的橡树，最初也是一颗简单的橡子。',
    'Expedition Party': '探险队',
    'Inventory Sorting': '库存分类',
    'It matches your complexion perfectly.': '它和你的肤色很相配。',
    'It has a protective coating to prevent forest fires and accidental discharge.': '它有一层保护涂层，以防止森林火灾和意外排放。',
    'Make sure to wear this belt at just the right moment.': '请在适当的时候系上这条腰带。',
    'Put it into a jar with vinegar and salt to create a tasty snack.': '把它和醋、盐一起放进罐子里，做成美味的小吃。',
    'Seemingly addictive, but comes with strange digestive complications.': '看起来会上瘾，但会有奇怪的消化并发症。',
    'Sort your bank by tier, type, and then rarity.': '按等级、类型和稀有性对银行进行分类。',
    'Sort your inventory by tier, type, and then rarity.': '按照等级、类型和稀有性来分类。',
    'The gaudy buckle is supposed to signify wealth.': '艳丽的带扣应该象征着财富。',
    'The most experienced spellcasters wear this cloak with pride.': '最有经验的施法者会以这种斗篷为傲。',
    'The perfect disguise for robbing trains.': '这是抢劫火车的完美伪装。',
    'Unlocks fifth guild order slot.': '解锁第五个公会订单插槽。',
    'Unlocks one more Jeweler.': '再解锁一个珠宝商。',
    'Unlocks the Weaponmaker.  They will help you craft different recipes.': '解锁武器制造者。他们会帮助你制作不同的配方。',
    'Wandering magi wear it to harness the elements.': '游荡的魔法师戴着它来驾驭大自然。',
    'Weaponmaker Worker': '武器制造工人',
    'Worn by initiates looking to find more steady work.': '用于寻找更稳定工作的提升者。',
    'You can assign as many heroes as you want to an expedition party, as long as they aren\'t already adventuring in a dungeon or on an expedition. Be careful though, more heroes in a party results in stat penalties!': '你可以指定任意数量的英雄加入探险队，只要他们没有在地下城或探险中。但是要小心，队伍中英雄越多会导致统计惩罚!',
    'A delicious spice in full support of energy drinks.': '一种美味的香料，全力支持功能饮料。',
    'A little poison will go a long way, so use it modestly.': '一点毒药就能解决很多问题，所以要谨慎使用。',
    'A little sticky, and a little nutty, but it makes everyone jealous.': '有点黏，有点疯狂，但这让每个人都嫉妒。',
    'A plain, standard issue helmet given to soldiers on their way to war.': '一种普通的、标准的头盔，发给上战场的士兵。',
    'A slightly worse version of the Storm Crystal.': '一个比风暴水晶稍差的版本。',
    'A weapon for the eternally angry and margarita fans alike.': '是永远愤怒的人和玛格丽塔粉丝的武器。',
    'Absolutely the worst kind of slime possible.': '绝对是最糟糕的黏液。',
    'Adorned with certain etchings that make it unmistakable.': '用某些蚀刻物装饰，使它不会弄错。',
    'Almost mirror-like, adventurers often confuse their enemies wearing these.': '几乎像镜子一样，冒险者经常戴着这个来迷惑他们的敌人。',
    'Also comes in black and white.': '也有黑色和白色。',
    'An introduction into the wide world of magic.': '介绍广阔的魔法世界。',
    'Armorer Worker': '装备工人',
    'As long as it covers my bald spot, I\'m happy.': '只要能盖住我的秃斑，我就很高兴了。',
    'Basic ingredients and techniques commonly used.': '普通的基本成分和工艺。',
    'Be grateful that this one doesn\'t come with that super annoying regional lockout.': '值得庆幸的是，这次没有出现超级恼人的区域封锁。',
    'Because what new sailors need is a heavy object that sinks.': '因为新水手需要的是沉下去的重物。',
    'Best to have health insurance before proceeding.': '在继续之前最好有健康保险。',
    'Better than the Month of May Staff, that\'s for sure.': '比五月份的员工要好，这是肯定的。',
    'Cannot Start Dungeon': '不能开始地下城',
    'Celebrities sell these crystals, promising relief from ailments.': '名人出售这些水晶，承诺可以缓解疾病。',
    'Chapped hands are a real problem, and these are the perfect solution.': '皲裂的手是一个真正的问题，而这些是完美的解决方案。',
    'Check out the newer version, the Greta Von Hauberk.': '看看最新的版本，格蕾塔·冯·锁伯克。',
    'Created in fertile farmland where great adventures seem to begin.': '创造在肥沃的农田，伟大的冒险似乎开始。',
    'Don\'t shove this in your bike spokes.': '别把这个塞到自行车辐条里。',
    'Ergonomically designed so you can snap while you sing.': '符合人体工程学的设计，这样你唱歌的时候就可以拍照了。',
    'Fairness is okay as long as I get what I want.': '只要我能得到我想要的，公平是可以的。',
    'Fresh from the forge, so treat them right.': '刚从铁匠铺出来，好好对待他们。',
    'Fun stories from former witches and warlocks.': '以前的巫师和术士的有趣故事。',
    'Gear Upgrade Available': '装备升级可用',
    'Gifted to the most prestigious of generals upon retirement.': '将在退休后送给最有声望的将军。',
    'Good for those on the run and trying to prove their innocence.': '这对那些在逃试图证明自己清白的人来说是好事。',
    'Has a handy pocket to keep bandanas and knives.': '有一个方便的口袋放手帕和刀。',
    'How to make long distance relationships with magma elementals work.': '如何与岩浆元素建立长距离关系。',
    'How to make your enemies dirty while staying squeaky clean.': '如何让你的敌人肮脏的同时保持干净。',
    'If this armor were any heavier, adventurers would collapse from the weight.': '如果这种盔甲再重一点，冒险家们就会因其重量而崩溃。',
    'If you spin the Wind Staff quickly over your head, you won\'t fly, but it will look really cool.': '如果你在头上快速旋转风杖，你不会飞起来，但它看起来真的很酷。',
    'Ingest this slime and you may hallucinate wildly.': '吞下这种粘液，你可能会产生疯狂的幻觉。',
    'It also comes in "morally grey."': '它也出现在《道德灰色》中。',
    'It does a much better job of preventing brain injuries than a rusty bucket ever could.': '它在防止脑损伤方面比生锈的水桶做得好得多。',
    'It is made of foam, smells like beer, and comes with a warning against bears, vikings, and lions.': '它是由泡沫制成的，闻起来像啤酒，还附有对熊、海盗和狮子的警告。',
    'It knows what you did last spring.': '它知道你去年春天做了什么。',
    'It may not look like much, but it does the job.  Eventually.': '它可能看起来不太像，但确实起作用了。最终。',
    'It might just be a piece of dirt.': '可能只是一堆脏东西。',
    'It\'s a dirty staff, but someone has got to use it.': '这东西很脏，但总得有人用。',
    'Legend states that these mythical gauntlets are awarded to dragon raiders and cheese hoarders.': '传说这些神秘的手套是授予龙袭击者和奶酪囤积者的。',
    'Manly men in northern regions are particularly suited for this pendant.': '北方地区有男子气概的男士特别适合这个吊坠。',
    'Might be a decoder ring, but it\'s hard to tell.': '可能是一个解码环，但很难说。',
    'Neve\'s Playbooks': '妮芙的剧本',
    'Pieces of the fabled ratmouse.': '传说中的老鼠的碎片。',
    'Not safe to own in houses made of glass.': '住在玻璃房子里不安全。',
    'Protect yourself against bag raiders with a handful of these.': '用这些来保护你自己免受背包袭击者的袭击。',
    'Provides strong protection, but limited mobility.': '提供强大的保护，但有限的机动性。',
    'Rarity crafting chances doubled and material costs removed.': '稀有锻造几率加倍，材料成本移除。',
    'Redirects directly to this recipe\'s details.': '直接重定向到此菜谱的详细信息。',
    'Ring has been mastered!': '戒指已经精通了！',
    'Sadly, these will not create more when cut in half.': '可悲的是，当切成两半时，这些将不会产生更多。',
    'Seeing is believing, but blocking with this shield doesn\'t hurt either.': '眼见为实，但用这个盾牌挡住也没有伤害。',
    'Punching Bag': '沙袋',
    'Smells like ale, and covered in syrup.': '闻起来像麦芽酒，还裹着糖浆。',
    'Sometimes the easiest way to win is to wait for your enemy to die.': '有时候，最简单的获胜方法就是等待敌人死去。',
    'Staunch magical defenders used these in ancient times.': '坚定的魔法守卫者在古代使用这些。',
    'Street performers have been dazzling audiences for years using this special staff.': '多年来，街头艺人利用这一特殊的工作人员让观众眼花缭乱。',
    'Suit up when dealing with these chunks.': '处理这些大块的时候要穿戴好。',
    'The beloved pendant of vegetarians and vegans.': '素食主义者和严格素食主义者心爱的吊坠。',
    'The exact opposite of The Everything Gauntlet.': '和"万能手套"正好相反。',
    'The history of this armor is mired in controversy.': '这种盔甲的历史一直饱受争议。',
    'The knuckles are padded with brass, which seems counterintuitive.': '指关节是用黄铜填充的，这似乎违反直觉。',
    'The perfect shoe for date night and stabbing people in the neck.': '这是约会之夜的完美鞋，还能刺伤别人的脖子。',
    'The Lakekeeper may be a bit rusty, but a little tetanus never hurt anyone.': '守护者可能有点生疏了，但小小的破伤风不会伤害任何人。',
    'The soldiers soldered this ring themselves.': '士兵们自己焊接了这枚戒指。',
    'The thumbs are green, as you would expect.': '如你所料，拇指是绿色的。',
    'These boots have odd properties that allow it to change form quickly.': '这些靴子有奇怪的特性，可以迅速改变形状。',
    'These gauntlets have never been touched, until now.': '这些手套从没被人碰过，直到现在。',
    'These wooden shoes are tiny, and have bits of romaine stuck inside.': '这些木鞋很小，里面有一些长叶植物。',
    'They kinda look like Lobster Chunks.': '它们看起来有点像龙虾块。',
    'This hat is perfect for summer days, where the sand is coarse, rough and irritating.': '这顶帽子非常适合夏天戴，因为夏天的沙子很粗糙，很粗糙，让人受不了。',
    'This helmet is extremely heat resistant, but it is also highly magnetic.': '这个头盔极具耐热性，但也具有很强的磁性。',
    'This item is an upgrade to gear equipped on another hero.': '此物品是另一个英雄装备的升级道具。',
    'This reactive armor says it reduces damage by 93%, but it\'s probably just marketing hype.': '这个反应装甲说它可以减少93%的伤害，但这可能只是市场炒作。',
    'This ring signifies that the wearer holds no allegiances.': '这枚戒指表示佩戴者不效忠任何一方。',
    'This shield will help you hold your ground, even in adverse situations.': '这个盾牌将帮助你坚守阵地，即使在不利的情况下。',
    'This tiara isn\'t for real princesses, but rather those who demand to be treated like one.': '这顶王冠不是为真正的公主准备的，而是为那些要求被当做公主对待的人准备的。',
    'This vest allows the wearer to move silently.': '这种背心可以让穿着者无声地移动。',
    'Turn the crank and see what happens.': '转动曲柄看看会发生什么。',
    'Use it.  Abuse it.  Lose it.  That\'s the Meager Sword Motto.': '使用它。滥用它。失去它。这是“穷剑”的座右铭。',
    'Use this against yourself before your enemies get the chance.': '在你的敌人有机会之前用这个对付你自己。',
    'View in Recipes': '在配方中查看',
    'Walk softly, and carry a big stick to impale your adversaries with.': '轻轻地走，拿一根大棒刺穿你的对手。',
    'Water Staff users can use floods in expertly timed, awe inspiring bursts of magic.': '水职员用户可以使用洪水在专业的时间，令人敬畏的魔法爆发。',
    'When a Shop Order is empty, you can select one of the available recipes below to permanently learn it allowing you to finish a new Shop Order. Choose wisely!': '当一个商店订单为空时，您可以选择下面的一个可用配方，以永久了解它，从而完成一个新的商店订单。做出明智的选择!',
    'Whoever named this slime probably used a thesaurus.': '给这种黏液命名的人可能用了辞典。',
    'Wisdom is knowing not to put tomatoes in a fruit salad.': '智慧就是知道不要把西红柿放进水果沙拉里。',
    'Works great for scrubbing sinks or avoiding the hoi polloi.': '非常适合擦洗水槽或避开民众。',
    'Worn by those who hide in plain sight.': '那些藏在眼皮底下的人。',
    'You have no heroes in your party.': '你们党里没有英雄。',
    'You\'ve been warned: don\'t smell it.': '我警告过你:不要闻它。',
    'View Market': '查看市场',
    'Start Dungeon': '开始地下城',
    'Submit': '提交',
    'Trophy': '奖杯',
    'Good': '不错',
    'Good Rarity': '不错的品质',
    'Insufficient Workers': '工人不足',
    'Hero Type': '英雄类型',
    'MOXIE': '勇气',
    'Auto-Contribute': '自动贡献',
    'Auto-Contribute to Orders': '自动贡献订单',
    ') of this item.': ') 对于此物品.',
    'and': '和',
    'All': '全部',
    'Common': '普通',
    'Good and below': '不错和以下的',
    'Great and below': '大师和以下的',
    'None': '无',
    'Great': '大师',
    'MIGHT': '强大',
    'Good Bandit Mask Crafted!': '制作了一个不错的强盗面具!',
    'Comfortable': '舒缓',
    'Compact': '紧凑',
    'Hotkeys': '快捷键',
    'Hero Equip': '英雄装备',
    'Equip this Trophy': '装备这个奖杯',
    'Grey': '灰色',
    'No hero has this trophy equipped.': '没有英雄装备过这个奖杯。',
    'Magenta': '品红',
    'Mom\'s Basement': '妈妈的地下室',
    'Quests Info': '任务信息',
    'Research Level': '研究等级',
    'Base Great Rate': '基础大师级几率',
    'Base Good Rate': '基础不错几率',
    'Base Epic Rate': '基础史诗级几率',
    'Base Time Rate': '基础时间几率',
    'Completed': '已完成',
    'Community College': '社区大学',
    'Cannot Complete Research': '无法完成研究',
    'Confirm Offering': '确认提供',
    'Ample Storage': '充足的存储',
    'Bigger Containers': '更大的容器',
    'Bulky Trunks': '笨重的树干',
    'Hero Already Questing': '英雄已经在探索了',
    'Material Capactity': '材料容量',
    'Next Reward': '下个奖励',
    'Retrieve Now for': '现在检索',
    'Essence': '精华',
    'Desynthesize': '分解',
    'A material used by the Magical Synthesizer to transform items and speed up time. Gained from desynthesis of rare items.': '魔法合成器使用的一种材料，用来转换物品和加速时间。从稀有物品的合成中获得。',
    'Unlocks another Weaponmaker.': '解锁另一个武器制造者。',
    'Unlocks an extra Armorer.': '解锁一个额外的装备师。',
    'This hero is already on a quest.': '这位英雄已经开始了一项任务。',
    'The Snake Hole': '蛇洞',
    'The Fishing Hole': '钓鱼洞',
    'It is a wall.  It has a hole.  You get milk from the hole.  What is so hard to understand about that?': '它是一堵墙。它有一个洞。你从洞里取牛奶。这有什么难理解的?',
    'Expedition parties earn gold by reaching new landmarks. The speed of their travel is based on their POW, while the distance they need to travel is based on their HP.': '探险队通过到达新的地标而获得金牌。 他们的行进速度取决于他们的战俘，而他们需要旅行的距离则取决于他们的生命力。',
    'This section requires items of': '本节要求以下物品',
    'Steam Pipe Trunk Venue': '蒸汽管道干线地点',
    'Recipe Rarity': '配方稀有度',
    'Not enough gold to complete research.': '没有足够的金子来完成研究。',
    'Fortune expires once Epic Shiny Gauntlets is crafted.': '一旦制作了史诗般的闪亮护手，财富就会过期。',
    'An odd distress call has been reported at the Crank Factory.  Beorn should investigate.': '据报道，曲柄工厂发出了一个奇怪的求救信号。 贝恩应该去调查。',
    'The Golden Catue is home to some of the most unseemly characters in the realm.  Titus will fit in just fine.': '金拱门是该领域中一些最不流行的角色的所在地。 泰特斯就很好了。',
    'Recipe Types': '配方类型',
    'You have no items available to donate.': '您没有物品可以捐赠。',
    'Museum': '博物馆',
    'Donate items of the appropriate rarity and forge enhancement to contribute to the museum.': '捐赠适当的稀有物品及制作精美的装饰品，为本馆作贡献。',
    'Quests have pre-defined hero setups and landmark goals. Complete quests to unlock new playbooks!': '任务具有预定义的英雄设置和里程碑目标。 完成任务即可解锁新剧本！',
    'Neve would like to get a new perspective.  She would like to take an elevator to the top of the Arch.': '尼芙想获得一个新的视角。她想乘电梯到拱门的顶端。',
    'It\'s the most exclusive Club in town.': '这是城里最高档的俱乐部。',
    'Cedric is hungry again.  Hopefully the ice cream machine isn\'t broken at the Arch.': '塞德里克又饿了。但愿冰激凌机没在拱门处坏掉。',
    'An energy drink in full support of delicious spices.': '一种能量饮料，充分支持美味的香料。',
    'Wooden Trophy': '木制奖杯',
    'Rainbow Trophy': '彩虹奖杯',
    'Potassium Trophy': '钾奖杯',
    'Molten Trophy': '熔融奖杯',
    'Desert Trophy': '沙漠奖杯',
    'Air Trophy': '空气奖杯',
    'Darkness Trophy': '黑暗奖杯',
    'An excellent choice for packing on a few extra pounds.': '这是增加几磅体重的绝佳选择。',
    'After defeating a boss, you\'ll unlock the next set of recipes. New recipes require new materials. Buy the Dungeon Levels perk from the market.': '在打败一个boss后，你将解锁下一组配方。新的配方需要新的材料。在市场上购买地下城等级奖励。',
    'Using this trinket requires a large amount of duty, or restraint, or maybe authority.': '使用这个饰品需要大量的责任、约束或权威。',
    'Unlock the "More Shop Orders" perk from the Market. This allows you to have two shop orders at once, and it allows you to have some choice in which recipes to gain first.': '解锁市场上的“更多商店订单”福利。这允许您同时获得两个商店订单，并且允许您选择首先获得哪些食谱。',
    'The minimum rarity this recipe will craft at.': '此配方制作的最低稀有度。',
    'The level of this trinket research.': '此饰品研究的等级。',
    'The amount of time needed to increment this trinket research.': '增加饰品研究所需的时间。',
    'Send a team to Groovy Grove II to start collecting the next tier of material. You may need to abandon Groovy Grove I if someone is adventuring there.': '派遣一个队伍到 奇妙的小树林 II 开始收集下一层材料。如果有人在 奇妙的小树林 I 进行冒险，您可能需要放弃它。',
    'Research Time': '研究时间',
    'MIND': '精神',
    'Knife has been mastered!': '小刀制作已精通！',
    'Belt has been mastered!': '腰带制作已精通！',
    'Mask has been mastered!': '面具制作已精通！',
    'You do not have the required materials needed to craft this recipe.': '您没有制作此配方所需的必需材料。',
    'Your search must contain at least two characters.': '您的搜索必须至少包含两个字符。',
    'Missing Required Materials': '缺少必需的材料',
    'Beta': 'Beta版',
    'Invalid Search Parameters': '无效的搜索参数',
    'Beorn Screen': '贝恩屏幕',
    'Animations': '动画',
    'Adventure Overview Screen': '冒险概述屏幕',
    ' Screen': '屏幕',
    'Will prompt you with a confirmation before closing the window or tab. Changes will take affect on next session.': '关闭窗口或标签前，将提示您确认。 更改将在下一个会话中生效。',
    'Unassign': '取消分配',
    'Revere Screen': '里维尔屏幕',
    'Reset Hotkey': '重置快捷键',
    'Reset All Hotkeys': '重置所有快捷键',
    'Recipe Screen': '配方屏幕',
    'Notification Size': '通知大小',
    'Merchant Orders Screen': '商人订单屏幕',
    'Neve Screen': '尼夫屏幕',
    'Merchant Mastery Screen': '商人精通屏幕',
    'Market Screen': '市场',
    'Inventory Screen': '库存屏幕',
    'Hero Overview Screen': '英雄概览屏幕',
    'Hall of Milestones Screen': '里程碑大厅屏幕',
    'Designates the duration a notification will remain present on the screen.': '指定通知将保持在屏幕上的持续时间。',
    'Choose whether notifications are rendered.': '选择是否呈现通知。',
    'Choose whether hotkeys are triggered.': '选择是否触发热键。',
    'Choose whether animations are played when navigating through content.': '选择在浏览内容时是否播放动画。',
    'Choose between a spacious sizing for notifications or a more compact sizing.': '选择宽敞的尺寸通知或更紧凑的尺寸。',
    'A list of all of your accomplishments.': '一张你所有成就的清单。',
    'You have crafted a good rarity Bandit Mask!': '你制作了一个不错稀有度的强盗面具!',
    'You have crafted an epic rarity Knife!': '你制作了一把史诗稀有度的刀!',
    'You are currently not autoselling any rarities of this item.': '你现在不能自动出售任何稀有物品。',
    'You are currently auto-selling all rarities (': '你现在正在自动销售所有稀有度物品 (',
    'You are currently auto-selling': '你现在是自动销售',
    'rarity for this item.': '稀有度对于这件物品。',
    'Orders can be made up of multiple parts. Complete all parts to complete the order.': '订单可以由多个部分组成。完成所有部件以完成订单。',
    'Order Parts': '部分订单',
    'Epic Knife Crafted!': '制作了一把史诗刀!',
    'You do not have the required workers free for this craft.': '你们没有这种工艺所需的空闲工人。',
    'Purchase the Merchant Tab from the Market': '从市场购买商人选项卡',
    'Equip Revere with a Knife to make her stronger.': '给里维尔装备一把刀，让她更强壮。',
    'Equip Revere with a Knife and Bandit Mask so she can clear Floor 2 of Groovy Grove. Higher floors gain material faster.': '给里维尔装备一把刀和强盗面具，这样她就可以清理奇妙的小树林的2楼了。更高的楼层获得材料更快。',
    'Continue completing orders until you unlock the Novice Cloak. If you need Bee Chunks, make sure Revere is adventuring.': '继续完成命令，直到你解锁新手披风。如果你需要蜜蜂肉块，确保里维尔在冒险。',
    'Completed orders let you gain new recipes. Unlock the Bandit Mask recipe in Shop Orders.': '已完成的订单可以让您获得新的配方。在商店订单中解锁强盗面具配方',
    'Complete your first guild order by submitting 5 Knives.': '提交5把刀完成你的第一份公会订单。',
    'Unlocks the Jeweler.  Even more recipes are now available for creation.': '解锁珠宝商。现在有更多的配方可供制作。',
    'Remaining Craft Time': '剩余的制作时间',
    'The amount of time remaining before this recipe is crafted.': '距离制作完成剩余的时间。',
    'Cancel crafting this recipe. Materials will be refunded.': '取消制作这个配方。材料将被退还。',
    'Cancel Crafting': '取消制作',
    'Your crafting slots are all in use, please remove a craft to continue.': '你的工艺槽都在使用中，请移除一件工艺品以继续。',
    'You have crafted a good rarity Knife!': '你制作了一把不错的稀有型刀!',
    'View null Recipes': '查看空配方',
    'Unlocks the second Crafting Slot.  Now you can create recipes from two different crafters at the same time.': '解锁第二个锻造槽。现在你可以从两个不同的工匠同时创建配方。',
    'Unlock this trophy by defeating bosses.': '击败boss解锁奖杯',
    'There are no recipes to unlock right now. Complete a shop order for the ability to unlock a new recipe': '现在还没有配方可以解锁。完成一个商店订单以获得解锁新配方的能力',
    'No Crafting Slots Available': '没有制造插槽可用',
    'Manually contributing from this menu will allow you to contribute higher rarity items.': '从这个菜单手动添加将允许您添加更高稀有度的物品。',
    'Good Knife Crafted!': '制作了一把不错的刀!',
    'Equip Boss Trophies': '装备Boss奖杯',
    'Enabling this feature will auto-contribute items to this order if they meet the requirements.': '启用该特性将自动将项目添加到该订单中，如果它们满足需求。',
    'Defeating bosses unlocks new trophies; refighting bosses levels up your trophies.': '打败boss可以解锁新的奖杯;再与boss战斗会提升你的奖杯。',
    'Contribute Manually from Inventory': '从库存中手动贡献',
    'Build the Tinker Hut to unlock this feature.': '建立修补匠小屋以解锁此功能。',
    'You do not have enough gold or materials.': '您没有足够的金子或材料。',
    'You can find more heroes by purchasing perks in the Market.': '您可以通过在市场上购买额外奖励来找到更多英雄。',
    'Unlock the adventure area Groovy Grove in the Market.': '在市场中解锁冒险区：奇妙的小树林。',
    'Send Revere on an adventure to start collecting materials.  Revere will stay in the dungeon until you cancel it.': '让里维尔去冒险，开始收集资料。在你取消之前里维尔会一直待在地下城里。',
    'More Heroes?': '更多的英雄?',
    'Cannot Purchase Perk': '不能购买福利',
    'Unlock the hero Revere in the Market.': '在市场中解锁英雄里维尔。',
    ' the Knife in your Inventory.': '你库存中的那把刀。',
    'Introduction': '介绍',
    'Craft a Knife.': '制作一把刀。',
    ' Your game is taking an extended period to load. This may be due to a slow connection, corrupted data or your browser blocking cookies/site data. You may also download your save and share with the developers on': '你的游戏加载时间较长。这可能是由于连接缓慢、数据损坏或浏览器阻塞cookies/站点数据造成的。您也可以下载您的保存并与开发人员分享',
    'A Merchant\'s Journey': '商人的旅程',
    'Adding Orders...': '正在添加订单...',
    'Armorer': '装备师',
    'Shop Orders': '商店订单',
    'Extra': '额外',
    'Unlocks the Armorer.  Recipes requiring their expertise can be made.': '解锁装备师。需要他们的专长才能做出配方。',
    'Opens up the Expeditions building.  Your heroes might be happy to have new things to do.': '打开探险大楼。你的英雄们可能很乐意有新事情做。',
    'Unlocks the merchant tab.  Complete Shop Orders to unlock new recipes.': '解锁商店标签。完成商店订单解锁新配方。',
    'Unlocks an additional Cogsmith.': '解锁一个额外的铁匠。',
    'Unlocks a second guild order slot.  You will be able to pick your recipes from now on.': '解锁第二个公会命令槽。 从现在开始，您将可以选择配方。',
    'This shop order is empty. Select a recipe below to get a new order. You will need to defeat the next boss if no recipes are available.': '该商店订单为空。 选择下面的配方以获取新订单。 如果没有可用的配方，您将需要击败下一个Boss。',
    'Take It To The Bank': '把它拿到银行去',
    'Perks you have already purchased from the Market.': '你已经从市场上购买的福利。',
    'Purchased Perks': '已购买福利',
    'Perks you can purchase from the Market.': '你可以从市场上买到福利。',
    'Town Perk': '城镇福利',
    'Third Slot': '第三插槽',
    'Second Slot': '第二插槽',
    'Perk': '福利',
    'Not A Dog Person': '不养狗的人',
    'Defeating the boss previous to this dungeon will unlock this boss dungeon.': '击败这个地下城之前的boss将解锁这个boss地下城。',
    'Start At Floor': '开始从层',
    'Show Enemy Party': '显示敌方',
    'Shaman': '萨满',
    'Select the heroes to send on this adventure.': '选择英雄来进行这次冒险。',
    'Not Available': '不可用',
    'Lightning Shaman': '闪电萨满',
    'Flood': '洪水',
    'Defeat bosses to unlock harder dungeons with new materials.': '击败boss，解锁更难的地下城与新材料。',
    'Cyan Curse': '青色诅咒',
    'Abandon All Dungeons': '放弃所有地下城',
    'Start At Highest Floor Reached': '从最高的楼层开始',
    'Blinkie': '眼罩',
    'Stinkie': '臭家伙',
    'Violet Death': '紫罗兰之死',
    'Alok comes from a wealthy family, and enjoys stealing worthless items from the poor.': '阿洛克来自一个富裕的家庭，喜欢从穷人那里偷走毫无价值的物品。',
    'Back And Fourth': '来来回回',
    'Bag': '包',
    'Bloodlust': '嗜血',
    'Beorn is the model all young warriors strive to become.  He\'s quite the celebrity.': '贝奥恩是所有年轻战士努力成为的榜样。他可是个名人。',
    'Blizzard': '暴风雪',
    'Caeda uses both her charm and charisma to get almost anything she wants.': '凯达用她的魅力和魅力得到几乎任何她想要的东西。',
    'Caster': '施法者',
    'Catastrophe': '灾难',
    'Cedric\'s parents died mysteriously, and he will do anything to find out what happened.': '塞德里克的父母神秘地死了，他将竭尽全力找出发生了什么事。',
    'Dig Deep': '深挖',
    'Equip your hero with items from your inventory.': '为您的英雄装备库存里面的物品。',
    'Equip your hero with trinkets from your inventory.': '为您的英雄装备库存中的小饰品。',
    'Grim knows what happened to Cedric\'s parents, but must keep the secret at all costs.': '格里姆知道塞德里克的父母出了什么事，但必须不惜一切代价保守秘密。',
    'Grogmar has a long list of offenses, and is hoping they don\'t catch up with him.': '格罗格玛的进攻很长，希望他们能跟上他的步伐。',
    'Icy Embrace': '冰冷的拥抱',
    'Infection': '传染',
    'Intercept': '拦截',
    'Just A Second': '等一下',
    'Lambug\'s family are poor fisherfolk, and she\'s looking to improve her lot in life.': '林虫的家人是可怜的渔民，她希望改善自己的生活。',
    'Light Hug': '沐浴春光',
    'Light Squeeze': '光爆',
    'Mage Moccasins': '法师的鹿皮软鞋',
    'Museum Donations': '博物馆捐赠',
    'Neve\'s goal in life is to spread the word of love, peace and harmony through magic.': '尼芙的人生目标是通过魔法传播爱、和平与和谐。',
    'No equipment available to equip in this slot.': '没有装备可以装备在这个插槽。',
    'No trinkets available to equip in this slot.': '没有小饰品可以装备在这个槽。',
    'Titus is totally a human, with real human skin and hair and everything.': '提图斯完全是一个人，拥有真正的人类皮肤和头发。',
    'Zoe was born with the gift of magic, and is unaware of the sheer power she possesses.': '佐伊天生就有魔法天赋，她并不知道自己拥有如此强大的力量。',
    'Troy is a magician\'s apprentice, looking to make a name for himself.': '特洛伊是一个魔术师的学徒，想要成名。',
    'Your game is taking an extended period to load. This may be due to a slow connection, corrupted data or your browser blocking cookies/site data. You may also download your save and share with the developers on': '你的游戏需要一段很长的时间来加载。这可能是由于一个缓慢的连接，损坏的数据或您的浏览器阻止cookies/网站数据。您也可以下载您的保存并与开发人员分享',
    'Your progress for total recipes mastered.': '你精通的配方总数的进度。',
    'These workers increase your guild worker capacity for crafting recipes.': '这些工人增加了工会工人制作配方的能力。',
    'There are no recipes available to master.': '没有配方可以掌握。',
    'The town looks empty - except for your Shop, of course. Perhaps the Action League can help with that?': '小镇看上去空无一人-当然，除了您的商店。 也许动作联盟可以帮上忙？',
    'The Skyfire Clan is a proud and noble race, and are expert weaponmakers.': '天火氏族是一个骄傲而高贵的种族，是制造武器的专家。',
    'The order in which actions will be taken during this adventure.': '在这次冒险中采取行动的顺序。',
    'The Cat\'s Meow are seeking a': '猫喵正在寻求',
    'Your expanded dropdown preferences are now saved for the "Materials Found In This Dungeon" dropdown for each Dungeon separately.': '现在，分别为每个地下城为“在此地下城中找到的材料”下拉菜单保存扩展的下拉首选项。',
    'Great Rarity': '大师级稀有率',
    'Sashimi Trophy': '生鱼片奖杯',
    'Synthesize': '合成',
    'You currently have no items stored in the bank.': '您目前在银行中没有任何物品。',
    'Confirm Smith': '确认铁匠',
    'Material Gain Rate': '材料增益率',
    'Crab Hammer': '蟹锤',
    'Cold Blooded': '冷血',
    'to all enemies and an additional 10% damage done for each banana found (banana for scale).': '对所有敌人和额外10%的伤害，每发现一个香蕉(香蕉为比例)。',
    'Titus saps life energy from the ally in front of him to apply Necrosis on his enemy counterpart. Necrosis deals 30': '提图斯从他面前的同伴身上吸取生命能量，对他的敌人施加坏死。坏死造成30',
    'Titus saps life energy from the ally behind him to apply Necrosis on his enemy counterpart. Necrosis deals 30': '提图斯从他身后的盟友身上吸取生命能量，对他的对手施加坏死。坏死造成30',
    'Tentacle Whip': '触手鞭',
    'Takes double damage on next attack.  Charges are removed when attacked.': '下次攻击造成双倍伤害。当被攻击时，冲锋被移除。',
    'Snack Break': '点心时间',
    'Shaman removes all debuffs from all allies.  Earth Shaman deals 100': '萨满从所有盟友身上移除所有减益效果。 大地萨满造成100',
    'Rising Phoenix': '凤凰升起',
    'Rapid Strikes': '快速攻击',
    'Purge': '清洗',
    'Provoke The Moxie': '激发勇气',
    'Provoke The Mind': '激发心灵',
    'Provoke The Mighty': '激发强者',
    'Prickly Personality': '独具个性',
    'Phoenix Fire': '凤凰火',
    'Paintbrush Knight attacks and performs an action based off its type - Might: Gain stacking self protective shield. Mindful: Heal self and gain a % heal buff. Moxious: Add debuff on enemy to take additional damage.': '画笔骑士攻击并执行基于其类型的动作-力量：获得堆叠式自我防护罩。 正念：自我治疗并获得％的治疗效果。 有毒：对敌人增加负面效果，使其受到额外伤害。',
    'Paintbrush Knight attacks an enemy unit in order for 100': '画笔骑士攻击敌方部队以造成100',
    'Once below 25% HP, Cinder Phoenix will turn into an egg and attempt to revitalize itself.': '生命值低于25％时，灰烬凤凰会变成一个蛋并试图使自己恢复活力。',
    'on the target\'s turn.': '在目标的回合。',
    'Niebieski heals all allies for 200': '涅别斯基治疗所有盟友200点',
    'Niebieski deals 200': '涅别斯基造成200',
    'Neve deals 60': '尼芙造成60',
    'Neve attacks the frontmost enemy for 100': '尼芙攻击最前方的敌人100',
    'Needle Barrage': '针幕',
    'Moxie Smash': '勇气粉碎',
    'Moxie Hero attacks will be focused on Zielony.  Zielony will not be attacked by other hero types.  Upon their death, Zielony will grant "Take My Knife!" to the Goblin King.  Take My Knife causes the Goblin King\'s regular attacks to damage the lowest HP enemy, and deal double damage to Moxie heroes.': '勇气英雄的攻击将集中在Zielony。 Zielony不会受到其他类型英雄的攻击。 朱丽娜死后将授予“拿我的刀！” 地精王。 拿我的刀导致地精王的定期攻击伤害最低生命值的敌人，并对勇气英雄造成双倍伤害。',
    'Monkey occasionally becomes hungry, and will hunt for food.  All negative status effects will be removed.': '猴子偶尔会饿，会去寻找食物。所有负面状态效果将被移除。',
    'Monkey deals 200% to frontmost enemy. Monkey then heals self for 200': '猴子对最前方的敌人造成200%的伤害。然后猴子治愈自己200',
    'Monkey deals 200% to frontmost enemy. Monkey then deals 200': '猴子对最前方的敌人造成200%的伤害。然后猴子造成200',
    'Mind Sniper': '心灵狙击手',
    'Mind Hero attacks will be focused on Niebieski.  Niebieski will not be attacked by other hero types.  Upon her death, Niebieski will grant "Take My Staff!" to the Goblin King.  Take My Staff heals the Goblin King on his turn, and deals double damage to Mind heroes.': '心灵英雄的攻击将集中在涅别斯基身上。 涅别斯基不会受到其他英雄类型的攻击。 涅比斯基死后，将授予“带我的职员！” 地精王。 带我的法杖在转身时治疗地精王，并对心灵英雄造成双倍伤害。',
    'Mind Control': '精神控制',
    'Mighty Blast': '强力爆炸',
    'Might Hero attacks will be focused on Czerwony.  Czerwony will not be attacked by other hero types.  Upon his death, Czerwony will grant "Take My Shield!" to the Goblin King.  Take My Shield reduces damage taken from every third attack by 100%, and deals double damage to Might heroes.': '强大英雄袭击的重点将放在切尔沃尼身上。 切尔沃尼将不会受到其他英雄类别的攻击。 切尔沃尼死后，将授予“接受我的盾牌”！ 地精王。 接受我的盾牌可使每三次攻击造成的伤害降低100％，并对强大英雄造成双倍伤害。',
    'Masterpiece': '杰作',
    'Loathing Oak deals 700': '厌恶橡树造成700',
    'Lich King Larry deals damage to all enemies equal to 2% of their max HP.': '巫妖王拉里对所有敌人造成的伤害等于其最大生命值的2％。',
    'Lich King Larry deals 200': '巫妖王拉里造成200',
    'Krakoptopus applies Mind Control to a random enemy.  Mind Control gains control of this hero\'s next special skill, using it against their team or for his benefit.': '克拉科普托普斯对一个随机敌人施加思维控制。 心灵控制控制该英雄的下一项特殊技能，将其用于对战队伍或为其谋取利益。',
    'Krakoptopus applies Cold Blooded.  Cold Blooded negates damage received from enemies on the next attack, and heals Krakoptopus for an equal amount instead.': '克拉科普托普斯是冷血动物。冷血者抵消敌人在下一次攻击时所受的伤害，并治疗克拉科普托普斯相同的伤害。',
    'Larry Jr explodes, dealing 300': '小拉里爆炸了，造成300',
    'Knife Throw': '扔飞刀',
    'Lasers': '激光',
    'Kingpin': '主要人物',
    'Hide Enemy Party': '隐藏敌人队伍',
    'Healing Aura': '治愈光环',
    'Gutter Punch': '天沟冲床',
    'Goblin Swipe': '哥布林滑动',
    'Goblin King gains a stack of Kingpin and gains a special buff every time another goblin dies.  Only one special buff can be active at a time.': '地精王获得一个堆叠主要人物，并在每一个地精死亡时获得一个特殊增益。一次只能激活一个特殊buff。',
    'Goblin King attacks the frontmost enemy unit for 200': '地精王攻击最前方的敌人单位200',
    'Goblin King attacks the frontmost enemy for 100': '地精王攻击最前面的敌人100',
    'Forgotten Wish': '被遗忘的愿望',
    'Dusty Alien deals 300': '灰暗的外星人造成300',
    'Distribution Djinn reallocates all enemies\' HP to be equal.': '分配灯神重新分配所有敌人的血量使之相等。',
    'Czerwony deals 200': '切尔沃尼造成200',
    'Czerwony attacks the nearest Moxie Hero for 800': '切尔沃尼攻击最近的英雄800',
    'Crusty Crab deals damage to the frontmost enemy equal to 25% of their max HP.': '硬壳螃蟹对最前方的敌人造成相当于其最大生命值25%的伤害。',
    'Cinder Phoenix applies Phoenix Fire on all enemy units.  Phoenix Fire deals 14': '灰烬凤凰对所有敌人单位施加凤凰火。凤凰火造成14',
    'Cedric gains Purity.  Purity increases max HP by 100': '塞德里克获得纯净。 纯净使最大生命值提高100',
    'Caeda applies Marked to the third enemy. Allies will focus their attacks on marked targets.': '凯达对第三个敌人进行标记。盟军将集中攻击有标记的目标。',
    'Bonesplosion': '骨头爆裂',
    'Blinkie gains Translucent.  Translucent reduces damage from the next attack by 100%.': '眨眼获得半透明。 半透明可使下一次攻击造成的伤害降低100％。',
    'Blank Canvas': '空白的画布',
    'Bananadine': '香蕉胺',
    'and applies Chilled.  If they are already Chilled,  this attack does 250': '并应用冷冻。如果他们已经被冷冻，这个攻击将达到250',
    'and an additional 40% healing done for each banana found (banana for scale).': '每发现一根香蕉，就会额外愈合40%的伤口(以香蕉为例)。',
    'and absorbs their type.': '并吸收他们的类型。',
    'Alok applies Paeon to all allies.  Paeon increases max HP by 200': '阿洛克对所有盟友使用潘神。施恩增加200点最大生命值',
    'Alok applies Madrigal to all allies. Madrigal increases Power by 25': '阿洛克对所有盟友使用牧歌。牧歌力量增加25点',
    'Worn to show prowess and cunning in battle.': '表现出在战斗中的英勇和狡猾。',
    'When grifting someone, make sure they aren\'t broke, or well connected.': '向某人求助时，请确保他们没有摔坏或连接良好。',
    'Wearing this trinket bestows a sense of pride and accomplishment.': '穿上小饰品可以给人一种自豪感和成就感。',
    'Used by only the most impassioned adventurers.': '仅由最热情的冒险家使用。',
    'To awaken its power, recite the following spell --  "Lorem ipsum dolor sit amet"': '要唤醒它的力量，背诵以下咒语——“锅巴锅巴你最帅，Git游戏我最爱”',
    'This weapon broke the mold.  Throw for the moon.': '这个武器打破了模子。扔到月亮上。',
    'This shield is lined with fur, so it will keep you warm at night.': '这盾牌内衬有毛皮，晚上可以保暖。',
    'This pendant looks good, and works amazingly well.': '这个吊坠看起来不错，效果也非常好。',
    'this helmet always feels like the first time, for the last time.': '这个头盔总让人觉得是第一次，最后一次。',
    'This garment is as cold as ice, but it\'s a sacrifice worth making for the power it gives.': '这件衣服冷得像冰，但为了它所带来的力量，牺牲是值得的。',
    'This belt has been left out in the open for way too long.': '这条皮带被放在外面太长时间了。',
    'There aren\'t many of these to go around, so make sure you treat this one with care.': '这样的东西并不多，所以一定要小心对待。',
    'The most luxurious possession and richest treasure most people will ever have.': '这是大多数人所拥有的最奢侈的财产和最富有的财富。',
    'The love for this ring is like a ticking clock.': '对这枚戒指的爱就像滴答作响的时钟。',
    'The leather in this belt was originally used in a pulley system.': '皮带上的皮革最初用于皮带轮系统。',
    'The ideal helmet for stunt performers and clowns alike.': '是特技演员和小丑的理想头盔。',
    'The fingers of these gloves are detachable, because sure, why not.': '这些手套的手指是可拆卸的，因为当然，为什么不呢?',
    'The favorite weapon of pirates and gunpowder enthusiasts.': '海盗和火药爱好者最喜欢的武器。',
    'The eyes in this mask seem droopy, and a little bloodshot.': '面具上的眼睛似乎下垂，还有一点充血。',
    'The color of these gauntlets baffle smiths and armorcrafters to this day.': '这些手套的颜色至今仍困扰着铁匠和盔甲工匠。',
    'The best excuse to have a second breakfast.': '再吃一顿早餐的最好借口。',
    'Sometimes the best shield against harm is your own principles.': '有时候对抗伤害最好的盾牌就是你自己的原则。',
    'Somehow funny, and spooky, all at the same time, like a comedy about a ghost.': '某种程度上滑稽，同时令人毛骨悚然，就像一部关于鬼魂的喜剧。',
    'Signifies a commitment to a difficult and taxing profession.': '象征着对困难和费力的职业的承诺。',
    'Set this blade to stun, instead of kill, and have a blast.': '将这把剑设置为击晕，而不是杀戮，并产生爆炸。',
    'Possibly fake.  It casts an odd shadow.  Could be a movie studio knockoff.': '可能是假的。它投射出奇怪的影子。可能是电影制片厂的山寨货。',
    'Politicians wear these so that they don\'t actually have to touch the great unwashed.': '政客们戴这个，这样他们就不用去碰那些不入流的人了。',
    'One of them appears to have a chip.': '其中一个好像有芯片。',
    'Particularly helpful when your wizards need food badly.': '当你的巫师非常需要食物的时候特别有用。',
    'Once worn by skilled laborers, many years ago.': '很多年前，曾经是熟练工人穿的。',
    'Not to be used as a floatation device.': '不能作为漂浮设备使用。',
    'Named after a torture device, this armor can cause hearing loss.': '这种盔甲以一种折磨人的装置命名，可以导致听力丧失。',
    'Matches perfectly with business socks, for business time.': '与商务袜完美搭配，适合商务时间。',
    'Manages to reflect light, even when covered in blood.': '即使满身是血，也能反射光线。',
    'Make sure to put the lotion on your skin before wearing this mask again.': '在再次使用此面膜之前，一定要在皮肤上涂上乳液。',
    'Made from flannel, it is especially deadly in the dry winter air.': '它由法兰绒制成，在干燥的冬季空气中尤其致命。',
    'Keeps your pants up.': '把你的裤子穿上。',
    'It\'s hard to have a fever when your head is missing.': '如果你的头不见了，就很难发烧了。',
    'Ideally speaking, we should all wear gloves before going to bed.': '理想情况下，我们睡觉前都应该戴手套。',
    'I\'m so upset.  How can I be expected to end the world when I can\'t even get Tommy to notice me?': '我很沮丧。汤米都没注意到我怎么能指望我毁灭世界呢?',
    'I\'m knifin around... cut, cut, cut, cut, cut.': '我在四处乱捅…砍，砍，砍，砍，砍。',
    'Honestly the weirdest of the staves, and kind of a boring superpower.': '说实话，他是最古怪的员工，还有一种无聊的超能力。',
    'Highly flammable.  Proceed with caution.': '高度易燃。 谨慎行事。',
    'Having two or three of these in a group will make a giant difference.': '一组中有两个或三个将产生巨大的变化。',
    'Great for protecting against the elements while in exile.': '非常适合在流亡时保护自己免受元素侵害。',
    'Given the opportunity, you should paint the back in black or really dark grey.': '如果有机会，您应该将背面涂成黑色或真正的深灰色。',
    'Frequently worn around the house, they don\'t often see the light of day.': '他们经常穿在房子周围，很少看到白天。',
    'Forged from the skull of a giant insect, this helmet smells like jerky and deception.': '这个头盔是用一只巨大昆虫的头骨锻造而成，闻起来有一股牛肉干和欺骗的味道。',
    'for Vol XXI: a special section on salads and croutons!': '对于卷XXI：关于沙拉和油煎面包块的特别部分！',
    'For some reason, this belt is constantly oscillating.': '由于某种原因，这条带子一直在摆动。',
    'For some reason, there\'s a spot for a gem on the thumb.  That\'s an odd choice.': '不知为什么，拇指上有个宝石的位置。这是个奇怪的选择。',
    'Especially popular in autumn with Basic Wand users.': '在秋季特别受普通魔杖使用者的欢迎。',
    'Easily able to cover an adventurer and a half.': '轻松涵盖冒险家半个人。',
    'Designed by a soft spoken judge who understands criminals quite well.': '由口语柔和的法官设计，他对罪犯非常了解。',
    'Contains the feather of an resurrected avian creature.': '包含一个复活的鸟类生物的羽毛。',
    'Contains a small amount of holy water, just in case.': '包含少量圣水，以防万一。',
    'Consider it a really sharp chill pill.': '认为它是一种非常锋利的镇静药。',
    'Concealed inside the lining is a healthy dose of tin foil, for obvious reasons.': '出于明显的原因，隐藏在衬里内部的是健康剂量的锡箔。',
    'Comes with a hydrophobic coating, so you can cause destruction in style.': '带有疏水涂层，因此可能会造成样式破坏。',
    'Clearly overcompensating for something.': '显然过度补偿了某些东西。',
    'Awarded to the best in competition.': '奖励给比赛中表现最好的选手。',
    'Also known in some circles as Everybody\'s Grudge.': '在某些圈子里也被称为人人嫉恨。',
    'All it takes is one match to start an explosion.': '一根火柴就能引起爆炸。',
    'A deep dive into best practices, but it is so dense most people don\'t know who the author is.': '本书深入探讨了最佳实践，但太过晦涩，以至于大多数人都不知道作者是谁。',
    'Soon it will be a water crystal.': '很快它就会变成一个水晶体。',
    'Snake': '蛇',
    'Perfect for inspiring a tropical heat wave.': '很适合引发热带热浪。',
    'Largely responsible for most of the heavy metal poisoning.': '造成大部分重金属中毒的主要原因。',
    'Just thinking about them makes my head itchy.': '一想到它们，我的头就会发痒。',
    'Gives you incredible strength and makes you feel invisible.': '给您不可思议的力量，让您感到无形。',
    'Burn them quickly.  They can smell your fear.': '他们迅速燃烧。他们能嗅到你的恐惧。',
    'There are green numbers on the inside.': '里面有绿色的号码。',
    'Swift Strike': '迅捷打击',
    'Regenerate': '再生',
    'Green Ooze heals itself for 200': '绿色软泥怪可以自己恢复200点生命',
    'Elf Adventurer deals 75% damage to the frontmost enemy and heals all allies for the damage dealt.': '精灵冒险者对最前端的敌人造成75％的伤害，并为所有盟友治疗造成的伤害。',
    'Especially lethal if you stab someone with it.': '如果您用它刺伤某人，尤其致命。',
    '100% Base Epic Rarity Chance': '100%基础史诗稀有几率',
    'While the Tree stood tall, a swift chop took it down. It\'s made with those splinters, of that tree, because it was chopped.': '那棵树挺立着，一斧子就把它砍倒了。它是用那棵树的碎片做的，因为它是被砍的。',
    'While the Djinn was an equalizer, it\'s equally dead now.': '虽然灯神曾经是一个均衡器，但它现在同样死了。',
    'to special attacks only.': '仅限特殊攻击。',
    'to normal attacks only.': '只对普通攻击有效。',
    'This trophy is nice, but maybe the real trophy is all of the Monkies we knifed along the way.': '这个奖杯很不错，但也许真正的奖杯是我们一路捅死的那些猴子。',
    'The Phoenix was strong, but now it will rise no more.': '凤凰很强大，但现在它不会再升起了。',
    'The Paintbrush Knight was a masterpiece, but now he\'s just a blank canvas.': '画笔骑士是杰作，但现在他只是一张空白的画布。',
    'The Lich was already dead, but you managed to kill him again anyway.  Being a single parent is tough.': '巫妖已经死了，但你还是杀了他。做一个单亲妈妈是很辛苦的。',
    'Krakoctopus captured the minds of many, but now he is no longer in control.  Have any good tempura recipes?': '克劳克托普斯吸引了许多人的注意，但现在他已不再处于控制之中。 有什么好天妇罗食谱吗？',
    'for normal attacks but reduces special attacks by -99': '用于普通攻击，但将特殊攻击降低-99',
    'Beorn gains Riposte.  Riposte negates the next incoming attack.  When consumed, Beorn will counterattack for 200': '贝恩获得还击。 还击否定了一个进入攻击。 消耗掉后，贝恩会反击200',
    'Although the Catcus was spikey, it\'s spikes will hurt no more. This trophy is much less sharp.': '尽管仙人掌很刺眼，但它的峰值不会再伤害到它了。 这个奖杯不那么锋利。',
    'You have crafted a great rarity Shiny Gauntlets!': '你已经制作了一个大师级稀有率闪亮手套!',
    'Great Shiny Gauntlets Crafted!': '大师级闪亮手套已制作!',
    'to all enemies.  Might Heroes take an additional 200': '对所有敌人。 强大英雄额外花费200',
    'to all enemies.': '所有的敌人。',
    'to an enemy when they attack it.': '当他们攻击敌人时。',
    'to fourth enemy': '对第四个敌人',
    'to frontmost enemy, 150': '对头号敌人，150',
    'to frontmost enemy. If Goblin King has "Take My Knife!" buff, this attack deals damage to the lowest HP enemy instead.': '对头号敌人。 如果地精王有“拿我的刀！” 增益，此攻击会对最低的HP敌人造成伤害。',
    'to second enemy, 100': '到第二个敌人，100',
    'to the front two enemies.': '到前面的两个敌人。',
    'to the frontmost enemy and applies Scorch.  Scorch deals 10': '到最前面的敌人，并施加灼烧。 灼烧造成10',
    'to the frontmost enemy for each debuff removed.': '对最前面的敌人的每次减益移除。',
    'to the frontmost enemy.': '向最前面的敌人。',
    'to the frontmost enemy.  If the enemy has Necrosis, Grim will heal himself for 100': '向最前面的敌人。如果敌人已经坏死，冷酷将会治疗自己100点',
    'to the lowest HP enemy.  If that enemy is a Mind Hero, Zielony deals an addtional 200': '给生命值最低的敌人。如果那个敌人是心灵英雄，朱丽娜造成额外的200',
    'to the lowest HP enemy.  If that enemy is below 50% health, Grogmar deals 300': '对最低生命值敌人。 如果该敌人的生命值低于50％，则格罗格玛造成300',
    'to the second enemy.': '第二个敌人。',
    'to the second enemy.  If they are Chilled, Revere deals 400': '第二个敌人。 如果他们变冷了，里维尔造成400',
    'to the third enemy.  If they are Scorched, Grogmar deals 400': '给第三个敌人。 如果他们被灼烧，格罗格玛造成400',
    'to the two lowest max HP enemy units.': '到两个最低的最大生命值敌方单位',
    'Translucent': '半透明',
    'to third enemy, and 50': '给第三个敌人，还有50',
    'Tree Wallop': '树墙',
    'Troy applies Regen to the frontmost ally.  Regen heals for 35': '特洛伊对最前线的盟友使用恢复。回复35生命值',
    'Troy heals all allies for 75': '特洛伊治疗所有盟友75',
    'Weaken Foes': '削弱敌人',
    'Troy heals the ally missing the most HP for 100': '特洛伊在100秒内治疗失去最多生命值的队友',
    'Zielony applies Weaken Foes to all enemies.  Weaken Foes increases damage taken by 1.5x for the next attack received.': '朱丽娜对所有敌人都施加削弱。在下一次攻击中增加1.5倍的伤害。',
    'Zielony deals 200': '朱丽娜造成200',
    'Zoe deals 200': '佐伊造成200',
    "Cloud Save": "云存储",
    "Commands": "命令",
    "Crank Factory": "曲柄厂",
    "Create a new party for an Expedition": "为远征创建新队伍",
    "Desynths Performed": "进行的分解",
    "Enchant your gear with runes to unlock bonuses for your heroes.": "用符文为你的装备附魔，为你的英雄解锁奖励。",
    "Endless Forest": "无尽的森林",
    "Epic Running Gloves": "史诗跑步手套",
    "Expedition Center": "探险中心",
    "Expeditions Performed": "进行的探险",
    "Forge & Contribute": "锻造与贡献",
    "Forge a base item and contribute it to the shop order, bypassing the need to forge an item manually.": "锻造基础项目并将其贡献给车间订单，无需手动锻造项目。",
    "Forges Performed": "进行锻造",
    "Fortune Slots": "幸运老虎机",
    "Fortunes Predicted": "运势预测",
    "Fuse Slots": "保险丝槽",
    "Fuses Performed": "执行的保险丝",
    "Git游戏": "Git游戏",
    "Grogmar would also like a new playbook, and has someone in mind to help him.": "格罗格玛还想要一本新的剧本，并且心目中有人帮助他。",
    "Hero Compare": "英雄比较",
    "Material Capacity": "材料容量",
    "Materials Quickview": "材料概览",
    "Museum Inspection": "博物馆检查",
    "Only Improvements": "只有改进",
    "Progress further in the game to unlock this feature": "在游戏中进一步进步以解锁此功能",
    "Resynths Performed": "进行了重新合成",
    "Runes": "符文",
    "s for": "为",
    "Save or Load from Cloud": "从云端保存或加载",
    "Save or load your game data from the Cloud using Playfab.": "使用 Playfab 从云端保存或加载您的游戏数据。",
    "Send your heroes out on expedition parties and gather rewards.": "派你的英雄参加远征队并收集奖励。",
    "Speed I": "速度 I",
    "Speed II": "速度 II",
    "Synth Boost": "合成器提升",
    "Titus's Ruin": "提图斯的废墟",
    "Unlocks a new quest expedition for Troy to complete, allowing for him to heal in a different way.": "为特洛伊解锁新的任务远征，让他以不同的方式治愈。",
    "Unlocks the ability to speed up dungeons, even faster.": "解锁加速地牢的能力，甚至更快。",
    "Unlocks the ability to speed up dungeons.": "解锁加速地下城的能力。",
    "Unlocks Troy's final quest.": "解锁特洛伊的最终任务。",
    "A slightly upgraded version of the Lightning Crystal.": "闪电水晶的略微升级版。",
    "Add Fortune": "添加财富",
    "All Hero Gear": "所有英雄装备",
    "Beorn's Redemption": "比奥恩的救赎",
    "6 Epic Balmungous": "6 史诗香脂",
    "6 Epic Dark Gauntlets": "6 史诗黑暗护手",
    "6 Epic Dignity": "6 史诗尊严",
    "6 Epic Formal Belt": "6 史诗正式腰带",
    "6 Epic Intense Purple Cuirass": "6 史诗级深紫色胸甲",
    "6 Epic Whimsical Helmet": "6 史诗异想天开的头盔",
    "Common Inpulsa Sciurus": "常见的 冲击松鼠",
    "Epic Apprentice Cloak": "史诗学徒披风",
    "B a NaN as!": "席一昂~蕉",
    "Chop Chop": "劈斩",
    "Monkey Hungry": "猴子饿了",
    "Normal Tree": "普通树",
    "Reduces damage taken to 1.": "将受到的伤害减至 1。",
    "Remaining times to go looking for food.": "剩下的时间去寻找食物。",
    "Searching for bananas.  Will come out of hiding when reduced to 0 HP.": "寻找香蕉。 当HP降至0时会从隐藏中出来。",
    "This is Bananas": "这是香蕉",
    "Time For Lunch": "午餐时间",
    "Adventure Completed": "冒险已完成",
    "You have successfully completed this adventure!": "你已经成功完成了这次冒险！",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

    //原样
    'Discord Server': 'Discord Server',
    'Bonerang': 'Bonerang',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "A list of all of your heroes and a quick overview of": "您所有英雄的清单以及以下内容的快速概述",
    "A special quest, just for ": "这是一个特别的任务，只是为了",
    "Additional Playbook for ": "额外的剧情",
    "Reputation:": "声望：",
    "Found in Groovy Grove ": "发现于奇妙的小树林 ",
    "Found in Spooky Spot ": "发现于幽灵点 ",
    "Patch ": "补丁",
    "Rodeo ": "竞技",
    "Hitman ": "杀手",
    "Grifter ": "骗子",
    "Hamster ": "仓鼠皮",
    "Heart ": "心灵",
    "Dancing ": "舞蹈",
    "Leather ": "羽毛",
    "General ": "普通",
    "Hunter ": "猎人",
    "Kitchen ": "厨房",
    "Lunar ": "太阴",
    "Marksman ": "射手",
    "Metal ": "金属",
    "Ornate ": "华丽的",
    "Panther ": "豹皮",
    'Maidens ': '少女',
    "Mole ": "鼹鼠皮",
    "Hairy ": "毛茸茸的",
    "Loving ": "爱心",
    "Master ": "大师",
    "Criminal ": "罪犯",
    "Mindful Bond ": "正念关系",
    "Mighty Allies ": "全能盟友",
    "Crafting ": "工艺",
    "Dungeon ": "地下城",
    "Dark ": "暗之",
    "Earth ": "地之",
    "Fire ": "火之",
    "Wind ": "风之",
    "Water ": "水之",
    "Fair ": "公正",
    "Princess ": "公主",
    "Magnetized ": "磁化",
    "Offer You Can't Re-Fuse": "你不能重新融合",
    "Formal ": "优等的",
    "Modest ": "温和的",
    "Other ": "其它",
    "Metallic ": "合金",
    "Coffee ": "咖啡",
    "Challenge ": "挑战",
    "Beach ": "海滩",
    "Golden ": "黄金",
    "Druidic ": "德鲁伊",
    "Tactical ": "战术",
    'Trapper ': '捕手',
    'Sailor ': '水手',
    'September ': '余烬',
    'Shining ': '闪亮',
    'Club ': '社团',
    'Spy ': '间谍',
    'Expert ': '专家',
    'Hugging ': '拥抱',
    'Bardic ': '吟游诗人的',
    'Dandy ': '上等',
    'Lifegiver ': '救生员',
    'Tinker ': '修补匠',
    'Ostium ': '开口',
    'Tacet ': '沉默',
    'Cool ': '酷',
    'Deathcaller ': '死亡召唤者',
    'Fancy ': '精致的',
    'Folium ': '叶形',
    'Cleaning ': '清洁',
    'Shooting ': '射击',
    'Chaplain ': '牧师',
    'Janitorial ': '清洁工的',
    'Practitioner ': '医生的',
    'Spoopy ': '间谍',
    'Frostflinger ': '弗罗斯特·弗林格',
    'Slayers ': '魔导士',
    'Frost ': '霜之',
    'Soldier ': '士兵',
    'Spellcasting ': '施法',
    'Super ': '超级',
    'Stormbringer ': '风暴使者',
    'Faithful ': '忠实的',
    'Stone ': '石头',
    'Support ': '支持',
    'Poison ': '毒药',
    'Planet ': '星球',
    'Plain ': '朴实的',
    'Pirate ': '海盗',
    'Pumpkin ': '南瓜',
    'Punching ': '穿孔的',
    'Cucumber ': '阴影',
    'Regular ': '普通的',
    'Running ': '奔跑',
    'Salty ': '盐焗',
    'Skull ': '骷髅',
    'Volto ': '护脸',
    'Paladin ': '游侠',
    'New ': '新',
    'Timing ': '同步',
    'Gardening ': '园艺',
    'Meager ': '劣质的',
    'Mega ': '巨型',
    'Mercenary ': '佣兵',
    'Journeyman ': '熟练工的',
    'Pristine ': '崭新的',
    'Shiny ': '光滑的',
    'Ignis ': '火之',
    'Outlaw ': '罪犯',
    'Oxygen ': '氧气',
    'Fan ': '粉丝',
    'Apprentice ': '学徒',
    'Rubber ': '橡胶',
    'Simple ': '简单的',
    'Whimsical ': '古怪的',
    'Assassin ': '刺客',
    'Bandit ': '强盗',
    'Black ': '黑色',
    'Boxing ': '拳击',
    'Fighting ': '战斗',
    'Flat ': '光滑的',
    'Fugitive ': '逃亡者',
    'Butter ': '黄油',
    'Standard ': '标准',
    'Old ': '旧',
    'Hidden ': '隐藏',
    'Great Hamster Vol ': '大师仓鼠卷',
    'Fishing ': '钓鱼',
    'Heavy Metal ': '重金属',
    'Extra ': '额外',
    'Powerful ': '强大的',
    'Earthslinger ': '寻地者',
    'Healthy ': '健康的',
    'Coal ': '煤炭',
    'Cobalt ': '深蓝',
    'Conveyor ': '传送',
    'Berserker ': '狂战士',
    'Must pass: ': '必须通过：',
    'Cowboy ': '牛仔',
    'Rust ': '生锈的',
    'Chef\'s ': '厨师的',
    'Leaded Zeppelin ': '齐柏林飞艇',
    'Noble ': '高贵的',
    'Novice ': '新手',
    'Feature ': '功能',
    'Trustworthy ': '可靠的',
    'Spells Vol': '魔法卷',
    'Sell': '出售',
    'Boss Realm': 'Boss领域',
    'Spooky Spot': '幽灵点',
    'Groovy Grove': '奇妙的小树林',
    'Creepy Crag': '毛骨悚然的峭壁',
    'Real Moxie': '真正的勇气',
    'Selected Playbook: ': '选择剧本：',
    'Found in Creepy Crag ': '发现于令人毛骨悚然的岩壁',
    'Auto-Sell Setting: ': '自动出售设置：',
    'Cauldroning ': '大锅 ',
    'Efficient Spells ': '高效法术 ',
    'Floor ': '层 ',
    'Rewards for ': '奖励针对',
    'Contribution Rarity: ': '捐献稀有度：',
    'Back to ': '返回',
    'Increase material storage capacity by ': '增加材料存储容量 ',
    'Landmark ': '地标 ',
    'Next Landmark: ': '下一个地标：',
    'Deal ': '造成 ',
    'but ': '但',
    'Lv1 ': '等级1 ',
    'This trophy awards +': '这个奖杯奖励 +',
    'Caddish Cactus deals ': '下流的仙人掌造成 ',
    'Grogmar deals': '格罗格玛造成',
    'Boost (': '提升 (',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    'Turn in 11 common, good, great, or epic items for bonuses to all ': '交出11件普通、不错、伟大物品或史诗物品作为奖励',
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    " ": "",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "\n": "",
    "\'s Playbooks": "的剧本",
    " Efficiency": " 效率",
    "their stats.": "他们的属性。",
    " Cost Removed": "成本移除",
    "All Commons": "全部普通",
    ' Chunks': '块',
    ' Essence': '精华',
    ' Slime': '黏液',
    ' crafts': '工艺品',
    ' Contributed': ' 已贡献',
    ' until next boost': ' 直到下一次提升',
    ' Contributions': '贡献',
    ' left': ' 剩余',
    'Goblin King will attack an additional unit for each stack of Kingpin.': '地精王每堆叠一次主要人物就攻击一个额外的单位。',
    'Goblin King will attack that enemy again for each stack of Kingpin.': '地精王每堆叠一次主要人物就再次攻击一个额外的单位。',
    'If no Moxie Heroes are available, Czerwony deals 200': '如果没有可用的勇气英雄，则切尔沃尼可获得200',
    ' to complete': ' 去完成',
    "Auto Sort Inventory": " 自动分类库存",
    '': '',
    '': '',
    '': '',
    '': '',
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^(\d+)\/(\d+)$/,
    /^(\d+) \/ (\d+)$/,
    /^(\d+):(\d+)$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)k$/,
    /^\s*$/,
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^(\d+) days, (\d+) hours, (\d+) minutes, (\d+) second$/, '$1 天, $2 小时, $3 分钟, $4 秒'],
    [/^(\d+) days, (\d+) hours, (\d+) minute, (\d+) second$/, '$1 天, $2 小时, $3 分钟, $4 秒'],
    [/^(\d+) days, (\d+) hours, (\d+) minutes, (\d+) seconds$/, '$1 天, $2 小时, $3 分钟, $4 秒'],
    [/^(\d+) days, (\d+) hours, (\d+) minutes, (\d+) seconds \(max$/, '$1 天, $2 小时, $3 分钟, $4 秒 \(最大'],
    [/^(\d+) days, (\d+) hour, (\d+) minutes, (\d+) seconds$/, '$1 天, $2 小时, $3 分钟, $4 秒'],
    [/^(\d+) days, (\d+) hour, (\d+) minutes, (\d+) second$/, '$1 天, $2 小时, $3 分钟, $4 秒'],
    [/^(\d+) days, (\d+) hours, (\d+) minute, (\d+) seconds$/, '$1 天, $2 小时, $3 分钟, $4 秒'],
    [/^(\d+) day, (\d+) hours, (\d+) minutes, (\d+) seconds$/, '$1 天, $2 小时, $3 分钟, $4 秒'],
    [/^(\d+) day, (\d+) hour, (\d+) minutes, (\d+) seconds$/, '$1 天, $2 小时, $3 分钟, $4 秒'],
    [/^(\d+) days (\d+):(\d+):(\d+)$/, '$1 天 $2:$3:$4'],
    [/^(\d+) Monster Trophies$/, '$1 怪物奖杯'],
    [/^Gaining ([\d\.]+) material every ([\d\.]+) seconds.$/, '每$2秒获得$1个材料。'],
    [/^LV(\d+) Glove$/, '等级 $1 手套'],
    [/^Boss (\d+) Defeated$/, 'Boss $1 被击败'],
    [/^(.+). You have (\d+).$/, '$1 . 你有 $2.'],
    [/^You have (\d+).$/, '你有 $1.'],
    [/^Grim deals (\d+)$/, '格里姆造成 $1'],
    [/^Revere deals (\d+)$/, '里维尔造成 $1'],
    [/^Lambug deals (\d+)$/, '林虫造成 $1'],
    [/^Level (\d+) \($/, '等级 $1 \('],
    [/^Level (\d+) \(([\d\.]+)$/, '等级 $1 \($2'],
    [/^Level (\d+)$/, '等级 $1'],
    [/^(\d+) Left$/, '$1 剩余'],
    [/^(.+) crafts remaining until mastery possible.$/, '$1 技能剩余直到可以掌握。'],
    [/^I. You have (.+).$/, 'I. 你有 $1.'],
    [/^II. You have (.+).$/, 'II. 你有 $1.'],
    [/^III. You have (.+).$/, 'III. 你有 $1.'],
    [/^IV. You have (.+).$/, 'IV. 你有 $1.'],
    [/^V. You have (.+).$/, 'V. 你有 $1.'],
    [/^(\d+) seconds$/, '$1 秒'],
    [/^Increases forge limits from \+(\d+) to \+(\d+).$/, '提高锻造上限从 \+$1 到 \+$2。'],
    [/^Purchase new recipes unlocked by leveling up\n(.+)your guild.$/, '购买通过升级公会解锁的新配方。'],
    [/^Purchase unique upgrades and perks that will expand your\n(.+)capabilities.$/, '购买独特的升级和特权，将扩展您的功能。。'],
    [/^Delete\n(.+)Data$/, '删除数据'],
    [/^Boss (\d+) Slain$/, 'Boss $1 被杀死了'],
    [/^Guild Level (\d+) Required$/, '要求公会等级 $1'],
    [/^(.+)Locked$/, '$1未解锁'],
    [/^(.+) Gold$/, '$1 黄金'],
    [/^This unit takes (.+) damage per stack at the start of its turn.$/, '该单位在其回合开始时每层受到 $1 伤害。'],
    [/^Your progress\n(.+)for donations to the Museum.$/, '你向博物馆捐款的进度。'],
    [/^Your progress for perks purchased from\n(.+)the Market.$/, '你从市场购买的福利的进度。'],
    [/^Your progress for total bosses\n(.+)defeated.$/, '你累计打败Boss的进度'],
    [/^Your progress for total recipes\n(.+)mastered.$/, '你掌握的配方总数的进度。'],

]);