/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Adventures': '冒险',
    'All Recipes': '所有配方',
    'Applicable Heroes': '适用英雄',
    'available for Upgrades.': '可用于升级。',
    'Back to Heroes': '返回英雄',
    'Back to Inventory': '返回库存',
    'Clear Save': '清除存档',
    'Details': '详情',
    'Download Save': '下载存档',
    'Dungeons': '地下城',
    'Equipment': '装备',
    'Exit Dungeon': '退出地下城',
    'Export Save': '导出存档',
    'Fetching...': '正在获取...',
    'Floor': '层',
    'Guilds': '公会',
    'Guild Workers': '公会工人',
    'Gold & Inventory': '黄金&库存',
    'Guild Recipes Available for Mastery': '公会配方可用于精通',
    'Market': '市场',
    'Inventory': '库存',
    'Heroes': '英雄',
    'Import Save': '导入存档',
    'Quests': '任务',
    'Sell All Commons': '出售所有公共物品',
    'Recipes': '配方',
    'Settings': '设置',
    'Sort Inventory': '库存排序',
    'Time Played': '游戏时长',
    'Town': '乡镇',
    'Turn Order': '回合顺序',
    'View Bank': '查看银行',
    'Upgrades': '升级',
    'Equip': '装备',
    'LVL': '等级',
    'Knife': '刀',
    'Knives': '刀',
    'Hats': '帽子',
    'Staff': '法杖',
    ' Locked': ' 未解锁',
    'A Cool Dark Chainmail': '酷黑锁子甲',
    'Armor': '盔甲',
    'Belts': '腰带',
    'Balmungous': '香脂',
    'Buzzblade': '嗡嗡之刃',
    'Cannonballer': '炮弹发射器',
    'Cauldroning': '大锅',
    'Clogs': '木屐',
    'Sell': '出售',
    'Shoes': '鞋子',
    'Sticks': '棍棒',
    'Staves': '权杖',
    'Squeaks': '吱吱声',
    'The Bank': '银行',
    'Titan': '泰坦',
    'Tomes': '书籍',
    'Type': '类型',
    'Vest': '背心',
    'Vests': '背心',
    'View Links & Resources': '查看链接&资源',
    'Worker': '工人',
    'Wisdom': '智慧',
    'You have': '你有',
    'Your Adventure Party': '你的冒险派对',
    'Gillian': '吉莉安',
    'Gloves': '手套',
    'Level': '等级',
    'Masks': '面具',
    'Informing the uninformed...': '通知不知情的人...',
    'Initializing game...': '正在初始化游戏...',
    'Crawling the dungeons...': '地牢爬行...',
    'Constructing buildings...': '构建建筑...',
    'Finalizing your progress...': '正在完成进度...',
    'Gathering materials...': '收集材料...',
    'Gathering your heroes...': '聚集你的英雄...',
    'Helmets': '头盔',
    'Jawstriker': '颚击者',
    'Item Being Equipped': '物品已被装备',
    'No materials currently in your inventory. Try the dungeons!': '您的库存中目前没有材料。去地下城试试!',
    'Not defeated yet.': '还没有被打败。',
    'Assembling the guilds...': '组装公会...',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    'Oren': '奥伦',

    //原样
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "Hitman ": "杀手",
    "Grifter ": "骗子",
    "Hamster ": "仓鼠皮",
    "Heart ": "心灵",
    "Leather ": "羽毛",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    " ": "",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "\n": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?[A-Za-z%]{0,2}(\s.C)?\s*$/, //12.34K,23.4 °C
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^\s*$/, //纯空格
    /^\d+(\.\d+)?[A-Za-z]{0,2}.?\(?([+\-]?(\d+(\.\d+)?[A-Za-z]{0,2})?)?$/, //12.34M (+34.34K
    /^(\d+(\.\d+)?[A-Za-z]{0,2}\/s)?.?\(?([+\-]?\d+(\.\d+)?[A-Za-z]{0,2})?\/s\stot$/, //2.74M/s (112.4K/s tot
    /^\d+(\.\d+)?(e[+\-]?\d+)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?$/, //2.177e+6 (+4.01+4
    /^(\d+(\.\d+)?(e[+\-]?\d+)?\/s)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?\/s\stot$/, //2.177e+6/s (+4.01+4/s tot
];
var cnExcludePostfix = [
    /:?\s*x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^(\d+) days, (\d+) hours, (\d+) minutes, (\d+) seconds$/, '$1 天, $2 小时, $3 分钟, $4 秒'],
    [/^(\d+) day, (\d+) hours, (\d+) minutes, (\d+) seconds$/, '$1 天, $2 小时, $3 分钟, $4 秒'],
    [/^(\d+) Monster Trophies$/, '$1 怪物奖杯'],
    [/^(\d+) Left$/, '$1 剩余'],
    [/^Boss (\d+) Slain$/, 'Boss $1 被杀死了'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);